"use client";
import {useGA4} from "@/features/ga4/provider";
import {GA4DailyTable} from "@/features/ga4/analytics-view";
import { useEffect,useState } from "react";
import { loadPerformanceTrend,mockTrendEndDate } from "@/lib/performance-trend";
import { readCampaignStore } from "@/lib/campaign-store";
import type { Period } from "@/types/domain";
import type { PerformanceTrend as Trend } from "@/types/mvp";
import { DataState } from "@/components/data-state";
import { number,won } from "@/lib/format";
function MockPerformanceTrend({advertiserId,period,revision=0}:{advertiserId:string;period:Period;revision?:number}){
 const [days,setDays]=useState<Period>(period),[campaign,setCampaign]=useState(""),[trend,setTrend]=useState<Trend|null>(null),[error,setError]=useState("");
 const campaigns=readCampaignStore(advertiserId).campaigns.filter(c=>c.status!=="DRAFT");
 useEffect(()=>{let active=true;setTrend(null);setError("");loadPerformanceTrend(advertiserId,days,campaign||undefined).then(t=>{if(active)setTrend(t)}).catch(e=>{if(active)setError((e as Error).message)});return()=>{active=false};},[advertiserId,days,campaign,revision]);
 return <section className="mvp-trend"><div className="mvp-heading"><div><span className="mvp-eyebrow">DAILY MOCK SNAPSHOT</span><h2>Performance Trend</h2></div><div className="mvp-controls"><label>Trend 기간<select value={days} onChange={e=>setDays(Number(e.target.value) as Period)}>{[7,14,30].map(n=><option key={n} value={n}>{n}D</option>)}</select></label><label>Trend Campaign<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">광고주 전체</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div></div><p>MOCK DATA · {mockTrendEndDate} 종료 합성 일자 데이터입니다. 선택 기간의 기존 집계와 합계가 일치하며 실제 일별 실적이 아닙니다.</p>{error?<DataState kind="error" message={error}/>:!trend?<DataState kind="loading"/>:<><div className="mvp-trend-insight"><b>{trend.detection.status}</b>{trend.detection.reasons.map(r=><span key={r}>{r}</span>)}</div><div className="mvp-charts"><LineChart title="Spend & Revenue" dates={trend.rows.map(r=>r.date)} series={[{name:"Spend",color:"#8170c9",values:trend.rows.map(r=>r.spend)},{name:"Revenue",color:"#3e9b81",values:trend.rows.map(r=>r.revenue)}]}/><LineChart title="Purchase" dates={trend.rows.map(r=>r.date)} series={[{name:"Purchase",color:"#3d688f",values:trend.rows.map(r=>r.purchases)}]}/></div><details><summary>일자별 지표 · {trend.scope}</summary><div className="mvp-scroll"><table><thead><tr>{["Date","Spend","Traffic","Purchase","Revenue","CPA","ROAS","Frequency"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{trend.rows.map(r=><tr key={r.date}><th>{r.date}</th><td>{won(r.spend)}</td><td>{number(r.traffic)}</td><td>{r.purchases}</td><td>{won(r.revenue)}</td><td>{r.cpa===null?"—":won(r.cpa)}</td><td>{r.roas===null?"—":r.roas.toFixed(1)+"%"}</td><td>{r.frequency}</td></tr>)}</tbody></table></div></details></>}</section>;
}
function LineChart({title,dates,series}:{title:string;dates:string[];series:{name:string;color:string;values:number[]}[]}){const max=Math.max(1,...series.flatMap(s=>s.values));return <figure><figcaption>{title}<span>{series.map(s=><small key={s.name} style={{color:s.color}}>{s.name}</small>)}</span></figcaption><svg viewBox="0 0 480 180" role="img" aria-label={`${title} · ${dates.length}일 Mock 추이`}><line x1="40" y1="145" x2="470" y2="145" stroke="#dfe4ed"/><line x1="40" y1="20" x2="470" y2="20" stroke="#edf0f5"/><text x="2" y="23" fontSize="10" fill="#728096">{number(max)}</text><text x="20" y="147" fontSize="10" fill="#728096">0</text>{series.map(s=><polyline key={s.name} fill="none" stroke={s.color} strokeWidth="2.5" points={s.values.map((v,i)=>`${40+i/Math.max(1,s.values.length-1)*430},${145-v/max*125}`).join(" ")}/>)}<text x="40" y="173" fontSize="11" fill="#728096">{dates[0]}</text><text x="470" y="173" fontSize="11" fill="#728096" textAnchor="end">{dates.at(-1)}</text></svg></figure>;}

export function PerformanceTrend(props:{advertiserId:string;period:Period;revision?:number}){const {mode,data}=useGA4();return <>{mode==="real"&&(data?.snapshot?<GA4DailyTable/>:<p>실제 GA4 일별 데이터 조회 실패. 아래는 MOCK AD DATA입니다.</p>)}<MockPerformanceTrend {...props}/></>;}
