import { test, expect } from "./fixtures";

test("퍼널, 소스, 세그먼트, Audience 조건, 캠페인 미리보기 동작", async ({ page }) => {
  const errors: string[] = [];
  const external: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => { if (new URL(request.url()).origin !== "http://localhost:3100") external.push(request.url()); });
  await page.goto("/funnel");
  const kpis = page.getByLabel("퍼널 핵심 지표");
  await expect(kpis).toContainText("1,284");
  await expect(kpis).toContainText("1,190");
  await page.getByText("유입 세션·행동 지표 보기").click();
  await expect(page.locator(".fw-detail-metrics")).toContainText("1,516");
  const stages = page.getByRole("group", { name: "퍼널 단계 선택" });
  await stages.getByRole("button", { name: /장바구니/ }).click();
  await expect(page.locator(".fw-stage-insight")).toContainText("장바구니 · 관찰");
  await expect(page.locator(".fw-stage-insight")).toContainText("결제진입 → 직접 구매");
  const filters = page.getByRole("group", { name: "유입 소스 필터" });
  await filters.getByRole("button", { name: "GPT Organic", exact: true }).click();
  await expect(kpis).toContainText("726");
  await expect(page.locator(".fw-source-table tbody tr")).toHaveCount(1);
  await filters.getByRole("button", { name: "GPT Ads", exact: true }).click();
  await expect(kpis).toContainText("558");
  await filters.getByRole("button", { name: "전체", exact: true }).click();
  const size = page.getByTestId("audience-size");
  await expect(size).toHaveText("742명");
  await page.getByRole("switch", { name: "Purchase 제외" }).uncheck();
  await expect(size).toHaveText("836명");
  await expect(page.getByText("구매 고객 94명 포함됨")).toBeVisible();
  await page.getByRole("switch", { name: "Purchase 제외" }).check();
  await page.getByLabel("Audience Window").selectOption("7");
  const week = await size.textContent();
  expect(week).not.toBe("742명");
  await page.getByLabel("Audience Window").selectOption("14");
  expect(await size.textContent()).not.toBe(week);
  await page.getByLabel("Audience Window").selectOption("30");
  await page.getByRole("checkbox", { name: "GPT Organic", exact: true }).uncheck();
  await page.getByRole("checkbox", { name: "GPT Ads", exact: true }).uncheck();
  await expect(size).toHaveText("0명");
  await page.getByRole("checkbox", { name: "GPT Organic", exact: true }).check();
  await expect(size).not.toHaveText("0명");
  await page.getByRole("checkbox", { name: /ViewContent/ }).uncheck();
  await page.getByRole("checkbox", { name: /AddToCart/ }).uncheck();
  await page.getByRole("checkbox", { name: /BeginCheckout/ }).uncheck();
  await expect(size).toHaveText("0명");
  const segments = page.getByRole("group", { name: "미구매 세그먼트 선택" });
  await segments.getByRole("button", { name: /장바구니 \/ 미구매/ }).click();
  const previewButton = page.getByRole("button", { name: "재방문 광고 Preview 열기" });
  await previewButton.click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("DEMO FORECAST");
  await expect(dialog).toContainText("장바구니 확인");
  await expect(dialog).toContainText("152명");
  await expect(dialog).toContainText("Purchase 제외된 세그먼트만 사용");
  await page.keyboard.press("Escape");
  await expect(dialog).not.toBeVisible();
  await expect(previewButton).toBeFocused();
  await segments.getByRole("button", { name: /결제진입 \/ 미구매/ }).click();
  await previewButton.click();
  await expect(dialog).toContainText("80명");
  await expect(dialog).toContainText("구매 계속하기");
  await page.getByRole("button", { name: "확인하고 닫기" }).click();
  expect(errors).toEqual([]);
  expect(external).toEqual([]);
});

test("광고주·기간 전환과 미지원 채널의 빈 상태", async ({ page }) => {
  await page.goto("/funnel");
  await expect(page.getByTestId("audience-size")).toHaveText("742명");
  await page.getByLabel("광고주 워크스페이스").selectOption("brand-b");
  await expect(page.getByTestId("audience-size")).toHaveText("511명");
  await expect(page.getByLabel("퍼널 핵심 지표")).toContainText("842");
  await page.getByRole("button", { name: "7일", exact: true }).click();
  await expect(page.getByTestId("audience-size")).toHaveText("122명");
  await page.getByLabel("Source Channel", { exact: true }).selectOption("naver");
  await expect(page.getByText("이 조합의 Mock 데이터는 아직 준비되지 않았습니다.", { exact: false })).toBeVisible();
  await expect(page.getByLabel("퍼널 핵심 지표")).not.toBeVisible();
  await page.getByLabel("Retargeting Channel", { exact: true }).selectOption("google");
  await expect(page.getByRole("heading", { name: "Naver → Google", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "GPT → Meta로 돌아가기" }).click();
  await expect(page.getByTestId("audience-size")).toHaveText("122명");
  await page.getByRole("button", { name: "30일", exact: true }).click();
  await expect(page.getByTestId("audience-size")).toHaveText("511명");
});

test("완성된 퍼널과 모달의 데스크톱·모바일 레이아웃", async ({ page }) => {
  for (const width of [1366, 1440, 1920, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    await page.goto("/funnel");
    await expect(page.getByTestId("audience-size")).toHaveText("742명");
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), `funnel at ${width}`).toBe(false);
    if (width === 1440 || width === 390) await page.screenshot({ path: `test-results/funnel-${width}.png`, fullPage: true });
    await page.getByRole("button", { name: "재방문 광고 Preview 열기" }).click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    const bounds = await dialog.boundingBox();
    expect(bounds!.width).toBeLessThanOrEqual(width);
    expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
    if (width === 1440) await page.screenshot({ path: "test-results/retargeting-preview.png" });
    await page.keyboard.press("Escape");
  }
});
