import {saved,test,expect} from "./fixtures";
const routes=["/dashboard","/funnel","/performance","/campaigns","/operations","/reports","/connections"];
test("전체 Journey·추천 초안·운영 변경·Reports 최신 상태·저장 복원",async({page})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(["warning","error"].includes(m.type()))errors.push(m.text()+" · "+m.location().url);});
 await page.goto("/dashboard");await page.getByLabel("광고주 워크스페이스").selectOption("brand-b");await page.getByRole("button",{name:"14일",exact:true}).click();
 await page.locator('nav a[href="/funnel"]').click();await page.getByRole("link",{name:/성과 개선에서 전체/}).click();await expect(page.getByLabel("광고주 워크스페이스")).toHaveValue("brand-b");await expect(page.getByRole("button",{name:"14일",exact:true})).toHaveAttribute("aria-pressed","true");await page.getByRole("button",{name:/추천 Recommended/}).click();await page.getByRole("button",{name:"캠페인 만들기",exact:true}).first().click();await expect(page.locator(".cs-origin")).toContainText("recommended");await expect(page.getByLabel("광고주 워크스페이스")).toHaveValue("brand-b");await page.getByLabel("Campaign Name",{exact:true}).fill("검수 Journey 캠페인");await page.getByRole("button",{name:"초안 저장",exact:true}).click();await saved(page);await page.reload();await expect(page.getByLabel("Campaign Name",{exact:true})).toHaveValue("검수 Journey 캠페인");await expect(page.getByLabel("광고주 워크스페이스")).toHaveValue("brand-b");await page.getByRole("button",{name:"Mock 캠페인 생성",exact:true}).click();await page.locator(".cs-list").getByRole("button",{name:"검수 Journey 캠페인",exact:true}).click();await page.getByRole("button",{name:"Mock 활성화",exact:true}).click();await page.getByRole("button",{name:"닫기",exact:true}).click();
 await page.getByRole("link",{name:/광고 운영 Operations/}).click();await expect(page.getByRole("button",{name:"검수 Journey 캠페인",exact:true})).toBeVisible();await page.getByLabel("Rule Name",{exact:true}).fill("검수 Pause");await page.getByLabel("Value 1",{exact:true}).fill("0");await page.getByRole("combobox",{name:"THEN Action",exact:true}).selectOption("Pause");await page.getByRole("combobox",{name:"Priority",exact:true}).selectOption("1");await page.getByRole("button",{name:"규칙 저장",exact:true}).click();await page.getByRole("combobox",{name:"Conflict Resolution",exact:true}).selectOption("Higher Priority Wins");await saved(page);await page.reload();await expect(page.locator(".op-saved-rule")).toContainText("검수 Pause");await page.locator(".op-queue article").filter({hasText:"Source · 검수 Pause"}).getByRole("button",{name:"Mock 적용",exact:true}).click();await expect(page.locator(".op-notice")).toContainText("APPLIED IN MOCK");await page.locator('nav a[href="/reports"]').click();await expect(page.locator(".mvp-inline-counts")).toContainText("Mock Active 0");await expect(page.locator(".mvp-two")).toContainText("검수 Journey 캠페인 · Status");await expect(page.locator(".mvp-two")).toContainText("APPLIED IN MOCK");await page.locator('nav a[href="/connections"]').click();await expect(page.getByLabel("광고주 워크스페이스")).toHaveValue("brand-b");await expect(page.getByRole("button",{name:"14일",exact:true})).toHaveAttribute("aria-pressed","true");await page.getByText("Advanced · 연결 아키텍처 및 기존 설정",{exact:true}).click();await page.getByRole("combobox",{name:"Data Density",exact:true}).selectOption("compact");await page.getByRole("button",{name:"설정 저장",exact:true}).click();await expect(page.getByRole("button",{name:"14일",exact:true})).toHaveAttribute("aria-pressed","true");expect(errors).toEqual([]);
});
for(const width of [1366,1024,768])test(`전체 Route ${width}px 가로 넘침·링크 대상·콘솔 검수`,async({page})=>{
 const errors:string[]=[],external:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(["error","warning"].includes(m.type()))errors.push(m.text()+" · "+m.location().url);});page.on("request",r=>{if(new URL(r.url()).origin!=="http://localhost:3100")external.push(r.url());});await page.setViewportSize({width,height:900});
 for(const route of routes){await page.goto(route);await expect(page.locator("main [aria-busy]")).toHaveAttribute("aria-busy","false");await expect(page.locator("main h1")).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const invalid=await page.locator('main a[href^="#"]').evaluateAll(links=>links.map(a=>a.getAttribute("href")!).filter(h=>h==="#"||!document.getElementById(h.slice(1))));expect(invalid).toEqual([]);await saved(page);await page.screenshot({path:`test-results/audit-${route.slice(1)||"overview"}-${width}.png`,fullPage:true});}
 expect(errors).toEqual([]);expect(external).toEqual([]);
});
