import {test,expect,loginAs} from "./fixtures";

test("로그인 1366·1024·768·390px 구조·키보드·잘못된 이메일",async({page})=>{
 await page.goto("about:blank");await page.context().clearCookies();
 for(const width of [1366,1024,768,390]){await page.setViewportSize({width,height:800});await page.goto("/login");const email=page.getByLabel("이메일",{exact:true}),cta=page.getByRole("button",{name:"로그인 링크 받기",exact:true});await expect(cta).toBeVisible();await expect(page.locator(".sidebar")).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const brand=await page.locator(".auth-brand-panel").boundingBox(),panel=await page.locator(".auth-login-panel").boundingBox();expect(panel!.y).toBeGreaterThanOrEqual(brand!.y+brand!.height);if(width===390){const box=await cta.boundingBox();expect(box!.y+box!.height).toBeLessThan(800)}await email.focus();await page.keyboard.press("Tab");await expect(cta).toBeFocused();await email.fill("not-an-email");await cta.click();await expect(email).toHaveAttribute("aria-invalid","true");await expect(page.getByRole("status")).toContainText("올바른 이메일");await email.fill("name@company.com");await expect(email).toHaveAttribute("aria-invalid","false");await page.screenshot({path:"test-results/login-"+width+".png",fullPage:true});}
});

test("전송 중 중복 차단·성공·마스킹·다른 이메일 및 오류 재시도",async({page})=>{
 await page.goto("about:blank");await page.context().clearCookies();let calls=0;let release:()=>void=()=>{};const wait=new Promise<void>(r=>{release=r});await page.route("**/api/auth/signin/resend**",async route=>{calls++;await wait;await route.fulfill({json:{url:"http://localhost:3100/login?sent=1"}})});await page.goto("/login");await page.getByLabel("이메일",{exact:true}).fill("hong@company.com");await page.getByRole("button",{name:"로그인 링크 받기",exact:true}).click();const sending=page.getByRole("button",{name:"로그인 링크 보내는 중...",exact:true});await expect(sending).toBeDisabled();await expect(page.locator(".auth-brand-panel")).toBeVisible();release();await expect(page.getByRole("heading",{name:"메일함을 확인해주세요."})).toBeVisible();expect(calls).toBe(1);await expect(page.locator(".auth-recipient")).toHaveText("hon***@company.com");await page.screenshot({path:"test-results/login-sent.png",fullPage:true});await page.getByRole("button",{name:"다른 이메일 사용"}).click();await expect(page.getByLabel("이메일",{exact:true})).toBeFocused();await expect(page.getByLabel("이메일",{exact:true})).toHaveValue("");await page.unroute("**/api/auth/signin/resend**");await page.route("**/api/auth/signin/resend**",route=>route.fulfill({json:{url:"http://localhost:3100/login?error=EmailSignIn"}}));await page.getByLabel("이메일",{exact:true}).fill("hong@company.com");await page.getByRole("button",{name:"로그인 링크 받기",exact:true}).click();await expect(page.getByRole("status")).toContainText("보내지 못했습니다");await expect(page.getByRole("button",{name:"다시 시도",exact:true})).toBeEnabled();await page.setViewportSize({width:390,height:800});await page.screenshot({path:"test-results/login-error-390.png",fullPage:true});await expect(page.locator(".auth-container")).not.toContainText("EmailSignIn");
});

test("로그인 상태 확인 중 폼 숨김·기존 세션의 관리자/광고주 진입 유지",async({page})=>{
 await page.goto("/login");await expect(page.getByTestId("admin-dashboard")).toBeVisible();await loginAs(page,"a@intentbridge.test");await page.goto("/login");await expect(page.getByTestId("advertiser-dashboard")).toBeVisible();await expect(page.locator(".workspace-lock")).toContainText("브랜드 A");await page.goto("about:blank");await page.context().clearCookies();let release:()=>void=()=>{};const wait=new Promise<void>(r=>{release=r});await page.route("**/api/auth/session",async route=>{await wait;await route.fulfill({json:{}})});await page.goto("/login");await expect(page.getByRole("status")).toHaveText("로그인 상태 확인 중...");await expect(page.getByLabel("이메일",{exact:true})).toHaveCount(0);release();await expect(page.getByLabel("이메일",{exact:true})).toBeVisible();
});

test("발송 안내 URL·만료 링크 오류·403 접근 제한 디자인",async({page})=>{
 await page.goto("about:blank");await page.context().clearCookies();await page.goto("/login?sent=1");await expect(page.getByRole("heading",{name:"메일함을 확인해주세요."})).toBeVisible();await page.goto("/login?error=Verification");await expect(page.getByRole("status")).toContainText("로그인 링크가 만료");await expect(page.locator(".auth-container")).not.toContainText("Verification");await loginAs(page,"a@intentbridge.test");await page.setViewportSize({width:390,height:800});const response=await page.goto("/settings");expect(response!.status()).toBe(403);await expect(page.getByRole("heading",{name:"이 페이지에 접근할 권한이 없습니다."})).toBeVisible();await expect(page.locator(".auth-brand-panel")).toBeVisible();await expect(page.locator("nav")).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:"test-results/login-denied-390.png",fullPage:true});
});

test("미저장 작업이 있는 세션 만료는 작업을 유지하고 새 창 로그인을 안내한다",async({page})=>{
 await page.goto("/campaigns");await page.route("**/api/workspace-data",route=>route.abort("failed"));await page.getByLabel("Campaign Name",{exact:true}).fill("만료 안내 검수");await expect(page.getByRole("button",{name:"저장 다시 시도"})).toBeVisible();await page.route("**/api/auth/session",route=>route.fulfill({json:{}}));await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.locator(".session-expired")).toContainText("로그인이 만료되었습니다.");await expect(page.locator(".session-expired a")).toHaveAttribute("target","_blank");await expect(page.getByLabel("Campaign Name",{exact:true})).toHaveValue("만료 안내 검수");
});
