import {saved,test,expect,type Page,type Download} from "./fixtures";
async function downloaded(d:Download){const stream=await d.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));return Buffer.concat(chunks).toString("utf8");}
async function setup(page:Page){await page.goto("/campaigns");await page.getByRole("combobox",{name:"세그먼트",exact:true}).selectOption("cart-14d");await page.getByLabel("Campaign Name",{exact:true}).fill("MVP Cart");await page.getByLabel("일 예산 (원)",{exact:true}).fill("10000");await page.getByRole("button",{name:"Mock 캠페인 생성",exact:true}).click();await page.locator(".cs-list").getByRole("button",{name:"MVP Cart",exact:true}).click();await page.getByRole("button",{name:"Mock 활성화",exact:true}).click();await page.getByRole("button",{name:"닫기",exact:true}).click();await page.getByRole("link",{name:/광고 운영 Operations/}).click();await expect(page.getByLabel("Rule Name",{exact:true})).toBeVisible();}
test("Connection Detail·Readiness·Empty·Settings·전역 광고주/기간 및 모든 Route",async({page})=>{
 const errors:string[]=[],external:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("request",r=>{if(new URL(r.url()).origin!=="http://localhost:3100")external.push(r.url());});
 await page.goto("/connections");await page.getByText("Advanced · 연결 아키텍처 및 기존 설정",{exact:true}).click();await expect(page.getByTestId("readiness-score")).toHaveText("36%");await expect(page.locator(".mvp> .mvp-scroll tbody tr")).toHaveCount(9);
 await page.locator(".mvp-link").filter({hasText:"Google Analytics 4"}).click();await expect(page.getByRole("dialog")).toContainText("Property ID");await expect(page.getByRole("dialog").locator("input")).toHaveCount(0);await expect(page.getByRole("dialog")).toContainText("80%");await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).toHaveCount(0);
 await page.getByRole("combobox",{name:"Connection Status",exact:true}).selectOption("READY FOR API");await expect(page.locator(".data-state.empty")).toBeVisible();await page.getByRole("combobox",{name:"Connection Status",exact:true}).selectOption("ALL");
 await page.getByRole("combobox",{name:"Data Density",exact:true}).selectOption("compact");await page.getByRole("combobox",{name:"Default Period",exact:true}).selectOption("7");await page.getByRole("button",{name:"설정 저장",exact:true}).click();await expect(page.locator(".app-shell")).toHaveAttribute("data-density","compact");await expect(page.getByRole("button",{name:"7일",exact:true})).toHaveAttribute("aria-pressed","true");
 await page.getByLabel("광고주 워크스페이스").selectOption("brand-b");await expect(page.locator(".brand-context")).toContainText("브랜드 B");
 for(const route of ["/dashboard","/funnel","/performance","/campaigns","/operations","/reports","/connections"]){await page.locator(`nav a[href="${route}"],nav a[href^="${route}?"]`).first().click();await expect(page.getByLabel("광고주 워크스페이스")).toHaveValue("brand-b");await expect(page.getByRole("button",{name:"7일",exact:true})).toHaveAttribute("aria-pressed","true");await expect(page.locator("nav [aria-current=page]")).toHaveCount(1);}
 await page.screenshot({path:"test-results/mvp-connections.png",fullPage:true});await saved(page);await page.reload();await expect(page.locator(".app-shell")).toHaveAttribute("data-density","compact");await page.getByText("Advanced · 연결 아키텍처 및 기존 설정",{exact:true}).click();await expect(page.getByRole("combobox",{name:"Default Period",exact:true})).toHaveValue("7");expect(errors).toEqual([]);expect(external).toEqual([]);
});
test("Executive Report·독립 HTML Export·모바일 레이아웃과 Empty",async({page})=>{await page.goto("/reports");await expect(page.locator(".mvp-kpis>div")).toHaveCount(6);await expect(page.locator(".mvp-insight")).toHaveCount(3);await expect(page.locator(".data-state.empty")).toContainText("아직 캠페인이 없습니다");const waiting=page.waitForEvent("download");await page.getByRole("button",{name:"Executive HTML Export",exact:true}).click();const html=await downloaded(await waiting);expect(html).toContain("DEMO FORECAST");expect(html).not.toContain("<nav");const report=await page.context().newPage();await report.setContent(html);await expect(report.getByRole("heading",{name:"Executive Report",exact:true})).toBeVisible();await report.screenshot({path:"test-results/mvp-executive-export.png",fullPage:true});await report.close();await page.screenshot({path:"test-results/mvp-reports.png",fullPage:true});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:"test-results/mvp-mobile.png",fullPage:true});});
test("Daily Trend 기간/Campaign·충돌 Priority·중복 강제 저장",async({page})=>{await setup(page);await page.getByRole("combobox",{name:"Trend 기간",exact:true}).selectOption("7");await page.locator(".mvp-trend summary").click();await expect(page.locator(".mvp-trend tbody tr")).toHaveCount(7);await page.getByRole("combobox",{name:"Trend Campaign",exact:true}).selectOption({label:"MVP Cart"});await expect(page.locator(".mvp-trend summary")).toContainText("Mock 클릭");await page.getByRole("combobox",{name:"Trend 기간",exact:true}).selectOption("14");await expect(page.locator(".mvp-trend tbody tr")).toHaveCount(14);await expect(page.locator(".mvp-charts svg")).toHaveCount(2);
 await page.getByLabel("Rule Name",{exact:true}).fill("Priority Scale");await page.getByRole("combobox",{name:"Priority",exact:true}).selectOption("1");await page.getByLabel("Value 1",{exact:true}).fill("0");await page.getByRole("button",{name:"규칙 저장",exact:true}).click();await expect(page.getByRole("combobox",{name:"Priority Scale Priority",exact:true})).toHaveValue("1");
 await page.getByLabel("Rule Name",{exact:true}).fill("Priority Reduce");await page.getByLabel("Value 1",{exact:true}).fill("0");await page.getByRole("combobox",{name:"THEN Action",exact:true}).selectOption("Decrease Budget");await page.getByRole("button",{name:"규칙 저장",exact:true}).click();await expect(page.locator(".op-saved-rule")).toHaveCount(2);
 const scale=page.locator(".op-queue article").filter({hasText:"Source · Priority Scale"});await expect(scale).toContainText("CONFLICT DETECTED");await expect(scale.getByRole("button",{name:"Mock 적용",exact:true})).toBeDisabled();await page.getByRole("combobox",{name:"Conflict Resolution",exact:true}).selectOption("Higher Priority Wins");await expect(scale.getByRole("button",{name:"Mock 적용",exact:true})).toBeEnabled();await page.getByRole("combobox",{name:"Conflict Resolution",exact:true}).selectOption("Skip Both");await expect(scale.getByRole("button",{name:"Mock 적용",exact:true})).toBeDisabled();
 await page.getByLabel("Rule Name",{exact:true}).fill("Scale copy");await page.getByLabel("Value 1",{exact:true}).fill("0");await expect(page.locator(".op-duplicate")).toContainText("유사한 운영 규칙");await page.getByRole("button",{name:"중복 확인 후 강제 저장",exact:true}).click();await expect(page.locator(".op-saved-rule")).toHaveCount(3);await page.screenshot({path:"test-results/mvp-operations.png",fullPage:true});});
test("Backup JSON · Merge 충돌 보존 · Replace 명시적 검토 · Invalid 차단",async({page})=>{await setup(page);await page.getByRole("link",{name:/데이터 연결 Connections/}).click();await page.getByText("Advanced · 연결 아키텍처 및 기존 설정",{exact:true}).click();const waiting=page.waitForEvent("download");await page.getByRole("button",{name:"Backup JSON 다운로드",exact:true}).click();const backup=JSON.parse(await downloaded(await waiting));expect(backup.schemaVersion).toBe("1.0");expect(backup.advertisers).toHaveLength(2);backup.advertisers[0].campaigns.campaigns[0].name="Imported Name";const upload=()=>page.getByLabel("Backup JSON 파일",{exact:true}).setInputFiles({name:"backup.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(backup))});await upload();await expect(page.getByRole("combobox",{name:"Import Mode",exact:true})).toHaveValue("merge");await expect(page.locator(".mvp-import-preview")).toContainText("기존 값 유지");await page.getByRole("button",{name:"검토한 Import 적용",exact:true}).click();await expect(page.locator("#data-backup")).toContainText("Import 완료");expect((await (await page.request.get("/api/workspaces/brand-a")).json()).campaigns[0].name).toBe("MVP Cart");await upload();await page.getByRole("combobox",{name:"Import Mode",exact:true}).selectOption("replace");await expect(page.getByRole("button",{name:"검토한 Import 적용",exact:true})).toBeDisabled();await page.getByRole("checkbox").check();await page.getByRole("button",{name:"검토한 Import 적용",exact:true}).click();await expect(page.locator(".mvp-import-preview")).toHaveCount(0);expect((await (await page.request.get("/api/workspaces/brand-a")).json()).campaigns[0].name).toBe("Imported Name");backup.schemaVersion="99";await upload();await expect(page.locator("#data-backup").getByRole("alert")).toContainText("INVALID BACKUP");await expect(page.getByRole("button",{name:"검토한 Import 적용",exact:true})).toHaveCount(0);});
