import "server-only";
import {AsyncLocalStorage} from "node:async_hooks";
import {installScopeResolver,type RuntimeScope} from "../runtime-scope";
import {requireAdvertiserAccess,requirePermission,sessionUser} from "./authorization";
import {db} from "./database";
import {loadWorkspaceSummary} from "../workspace-summary";
import type {Period} from "@/types/domain";
const scopes=new AsyncLocalStorage<RuntimeScope>();installScopeResolver(()=>scopes.getStore());
export async function adminWorkspaceSummaries(period:Period){const user=await requirePermission("VIEW_ALL_ADVERTISERS");const rows=await db.advertiser.findMany({where:{status:"ACTIVE"},take:100,orderBy:{id:"asc"}});const [documents,settings]=await Promise.all([db.workspaceDocument.findMany({where:{advertiserId:{in:rows.map(a=>a.id)},OR:[{key:{startsWith:"intentbridge:campaigns:"}},{key:{startsWith:"intentbridge:operations:"}}]},take:200}),db.userSetting.findMany({where:{userId:user.id},take:10})]);const fixtures={advertisers:rows.map(a=>({...a.mockData as RuntimeScope["fixtures"]["advertisers"][number],id:a.id,name:a.name,industry:a.industry,productName:a.productName}))};return scopes.run({fixtures,advertisers:rows.map(({id,name,industry,productName})=>({id,name,industry,productName})),user:sessionUser(user),documents:new Map([...documents,...settings].map(d=>[d.key,JSON.stringify(d.payload)]))},()=>Promise.all(rows.map(a=>loadWorkspaceSummary({advertiserId:a.id,period}))));}
export async function workspaceSummary(id:string,period:Period){const {user,advertiser}=await requireAdvertiserAccess(id);const [documents,settings]=await Promise.all([db.workspaceDocument.findMany({where:{advertiserId:id,key:{in:[`intentbridge:campaigns:v1:${id}`,`intentbridge:operations:v1:${id}`]}},take:2}),db.userSetting.findMany({where:{userId:user.id},take:10})]);const entry={...advertiser.mockData as RuntimeScope["fixtures"]["advertisers"][number],id,name:advertiser.name,industry:advertiser.industry,productName:advertiser.productName};return scopes.run({fixtures:{advertisers:[entry]},advertisers:[{id,name:entry.name,industry:entry.industry,productName:entry.productName}],user:sessionUser(user),documents:new Map([...documents,...settings].map(d=>[d.key,JSON.stringify(d.payload)]))},()=>loadWorkspaceSummary({advertiserId:id,period}));}
