import {transaction} from "./transaction";
import {requestContext} from "./request-context";
import {enforceRate} from "./request-protection";
import {validTarget} from "../operations-store";
import {validGuardrail} from "../operations-guardrail";
import "server-only";
import {db} from "./database";
import {AccessError,requireAdvertiserAccess,requirePermission,requireUser,sessionUser} from "./authorization";
import type {Prisma} from "@prisma/client";
import type fixture from "@/mock/mock-data.json";
type fixtureType=typeof fixture;
import {isCampaign,isCampaignDraft} from "../campaign-store";
import {validSaved} from "../simulation-library";
import {validRule} from "../operations-store";
import {validAppSettings} from "../app-settings";
export function keyScope(key:string){const parts=key.split(":");if(key==="intentbridge:settings:v1")return {kind:"settings",advertiserId:null};if(parts[0]!=="intentbridge"||parts[2]!=="v1"||!parts[3]||!['campaigns','operations','simulation-library','simulation'].includes(parts[1]))throw new AccessError(400,"저장 항목을 확인하세요.");if(parts[1]!=="simulation"&&parts.length!==4||parts[1]==="simulation"&&(parts.length!==7||!["7","14","30"].includes(parts[4])||parts[5]!=="chatgpt"||parts[6]!=="meta"))throw new AccessError(400);return {kind:parts[1],advertiserId:parts[3]};}
function inspect(value:unknown,id:string|null,depth=0){if(depth>25)throw new AccessError(400);if(value&&typeof value==="object")for(const [key,item]of Object.entries(value)){if(/(password|private.?key|client.?secret|access.?token|refresh.?token|api.?key|^secret$|^token$|^__proto__$|^constructor$|^prototype$)/i.test(key)||key==="advertiserId"&&id!==null&&item!==id)throw new AccessError(400,"저장 데이터의 광고주 또는 필드를 확인하세요.");inspect(item,id,depth+1);}}
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
function validate(kind:string,payload:unknown,id:string|null){inspect(payload,id);if(kind==="operations"&&record(payload)){if(!record(payload.targets)||!record(payload.guardrails)||!Object.values(payload.targets).every(v=>validTarget(v as never))||!Object.values(payload.guardrails).every(v=>validGuardrail(v as never)))throw new AccessError(400);}if(kind==="settings"){if(!validAppSettings(payload))throw new AccessError(400);return;}
 if(kind==="campaigns"){if(!record(payload)||payload.version!==1||!Array.isArray(payload.campaigns)||!payload.campaigns.every(c=>isCampaign(c,id!))||!Array.isArray(payload.drafts)||!payload.drafts.every(d=>isCampaignDraft(d,id!))||payload.draft!==null&&!isCampaignDraft(payload.draft,id!)||!Array.isArray(payload.versions)||!payload.versions.every(v=>record(v)&&typeof v.id==="string"&&v.advertiserId===id&&isCampaign(v.snapshot,id!)))throw new AccessError(400,"캠페인 형식을 확인하세요.");}
 if(kind==="operations"&&(!record(payload)||payload.schema!==1||!Array.isArray(payload.rules)||!payload.rules.every(validRule)||!Array.isArray(payload.history)||!payload.history.every(h=>record(h)&&typeof h.id==="string"&&h.advertiserId===id&&isCampaign(h.before,id!)&&isCampaign(h.after,id!))||!Array.isArray(payload.alerts)||!payload.alerts.every(a=>record(a)&&typeof a.id==="string"&&a.advertiserId===id)))throw new AccessError(400,"운영 데이터 형식을 확인하세요.");
 if(kind==="simulation-library"&&(!Array.isArray(payload)||!payload.every(s=>validSaved(s,id!))))throw new AccessError(400,"예측 형식을 확인하세요.");
 if(kind==="simulation"&&payload!==null&&(!record(payload)||!record(payload.levers)||!record(payload.forecast)||payload.forecast.advertiserId!==undefined&&payload.forecast.advertiserId!==id||!Object.values(payload.levers).every(v=>typeof v==="number"&&Number.isFinite(v)&&Math.abs(v)<=100)))throw new AccessError(400);
}
export async function bootstrap(){const user=await requireUser();const rows=await db.advertiser.findMany({where:{status:"ACTIVE",...(user.role==="SUPER_ADMIN"?{}:{members:{some:{userId:user.id}}})},orderBy:{id:"asc"},take:100});const settings=await db.userSetting.findMany({where:{userId:user.id},take:10});return {user:sessionUser(user),fixtures:{advertisers:rows.map(a=>({...a.mockData as fixtureType["advertisers"][number],id:a.id,name:a.name,industry:a.industry,productName:a.productName}))},documents:[...settings.map(s=>({key:s.key,payload:s.payload,revision:s.revision}))]};}
export async function readWorkspace(id:string){const {advertiser,user}=await requireAdvertiserAccess(id);const campaigns=await db.campaign.findMany({where:{advertiserId:id},take:100,orderBy:{id:"asc"}}),simulations=await db.savedSimulation.findMany({where:{advertiserId:id},take:100,orderBy:{id:"asc"}});return {advertiser:{id:advertiser.id,name:advertiser.name,status:advertiser.status},campaigns:campaigns.map(c=>c.payload),simulations:["SUPER_ADMIN","MANAGER"].includes(user.role)?simulations.map(s=>s.payload):[]};}
async function persistDocument(tx:Prisma.TransactionClient,input:{key:string;payload:unknown;revision:number}){const {key,payload,revision}=input;if(typeof key!=="string"||!Number.isSafeInteger(revision)||revision<0)throw new AccessError(400);const {kind,advertiserId}=keyScope(key);const user=advertiserId?(await requireAdvertiserAccess(advertiserId,kind==="operations"?"MANAGE_OPERATIONS":"MANAGE_CAMPAIGN")).user:await requirePermission("MANAGE_SETTINGS");validate(kind,payload,advertiserId);const value=(payload??{}) as Prisma.InputJsonValue;
 const prior=advertiserId?await tx.workspaceDocument.findUnique({where:{advertiserId_key:{advertiserId,key}}}):await tx.userSetting.findUnique({where:{userId_key:{userId:user.id,key}}});if(kind==="campaigns"&&record(payload)&&Array.isArray(payload.campaigns)){const old=prior&&record(prior.payload)&&Array.isArray(prior.payload.campaigns)?prior.payload.campaigns:[];if(payload.campaigns.length>old.length)await enforceRate("campaign",user.id);}if(kind==="operations"&&record(payload)&&Array.isArray(payload.history)){const old=prior&&record(prior.payload)&&Array.isArray(prior.payload.history)?prior.payload.history:[];if(payload.history.length>old.length)await enforceRate("operation",user.id);}if((prior?.revision??0)!==revision)throw new AccessError(409,"다른 화면에서 데이터가 변경되었습니다. 현재 초안을 보관한 후 새로고침해 주세요.");
 if(advertiserId){if(prior){const result=await tx.workspaceDocument.updateMany({where:{advertiserId,key,revision},data:{payload:value,revision:{increment:1}}});if(!result.count)throw new AccessError(409);}else await tx.workspaceDocument.create({data:{advertiserId,key,payload:value,revision:1}});
 const p=payload as Record<string,unknown>;const sync=async(model:"campaign"|"campaignDraft"|"campaignVersion"|"savedSimulation"|"automationRule"|"operationHistory"|"alert",items:unknown[])=>{const data=items.map(item=>{const r=item as Record<string,unknown>;return {id:String(r.id??r.draftId),advertiserId,payload:item as Prisma.InputJsonValue};});const delegate=tx[model] as unknown as {deleteMany(args:{where:{advertiserId:string}}):Promise<unknown>;create(args:{data:{id:string;advertiserId:string;payload:Prisma.InputJsonValue}}):Promise<unknown>};await delegate.deleteMany({where:{advertiserId}});if(data.length)await (tx[model] as unknown as {createMany(args:{data:typeof data}):Promise<unknown>}).createMany({data});};
 if(kind==="campaigns"){await sync("campaign",p.campaigns as unknown[]);await sync("campaignDraft",p.drafts as unknown[]);await sync("campaignVersion",p.versions as unknown[]);}
 if(kind==="operations"){await sync("automationRule",p.rules as unknown[]);await sync("operationHistory",p.history as unknown[]);await sync("alert",p.alerts as unknown[]);}
 if(kind==="simulation-library")await sync("savedSimulation",payload as unknown[]);
 }else if(prior){const result=await tx.userSetting.updateMany({where:{userId:user.id,key,revision},data:{payload:value,revision:{increment:1}}});if(!result.count)throw new AccessError(409);}else await tx.userSetting.create({data:{userId:user.id,key,payload:value,revision:1}});
 await tx.auditLog.create({data:{requestId:requestContext()?.requestId,actorUserId:user.id,advertiserId,action:kind==="operations"&&record(payload)&&Array.isArray(payload.history)&&payload.history.length>(prior&&record(prior.payload)&&Array.isArray(prior.payload.history)?prior.payload.history.length:0)?"AUTOMATION_MOCK_APPLY_OR_ROLLBACK":kind==="operations"?"OPERATIONS_SAVED":"DATA_SAVED",resource:key,...(prior?{before:prior.payload as Prisma.InputJsonValue}:{}),after:value}});return {key,revision:revision+1};
}

export async function writeDocuments(documents:{key:string;payload:unknown;revision:number}[],intent?:unknown){const user=await requireUser();if(!Array.isArray(documents)||!documents.length||documents.length>500||new Set(documents.map(d=>d?.key)).size!==documents.length)throw new AccessError(400);for(const d of documents){if(!d||typeof d.key!=="string")throw new AccessError(400);const {kind,advertiserId}=keyScope(d.key);if(advertiserId)await requireAdvertiserAccess(advertiserId,kind==="operations"?"MANAGE_OPERATIONS":"MANAGE_CAMPAIGN");else await requirePermission("MANAGE_SETTINGS");validate(kind,d.payload,advertiserId);}if(intent!==undefined&&intent!=="import")throw new AccessError(400);if(intent==="import"||documents.length>2)await enforceRate("import",user.id);return transaction(async tx=>{const results=[];for(const d of documents)results.push(await persistDocument(tx,d));return {documents:results};},{actor:user.id,scope:"workspace-batch",input:documents});}
export async function writeDocument(input:{key:string;payload:unknown;revision:number}){return (await writeDocuments([input])).documents[0];}
