import {test} from "node:test";
import assert from "node:assert/strict";
import {getDashboard} from "../lib/dashboard";
import {loadFunnelWorkspace} from "../lib/funnel";
import {loadPerformanceBaseline} from "../lib/simulation/baseline";
import {diagnose,simulate} from "../lib/simulation";
import {getRecommendations} from "../lib/recommendations";
import {loadCampaignWorkspace,performanceHandoff,newCampaignDraft,evaluateCampaign} from "../lib/campaign-service";
import {saveCampaign,changeCampaignStatus} from "../lib/campaign-store";
import {loadExecutiveReport} from "../lib/executive-report";
import {saveConflictResolution} from "../lib/operations-store";
import {loadOperations} from "../lib/operations-engine";
import {saveAutomationRule,applyOperation} from "../lib/operations-history";
import {scenarios,zeroLevers} from "../data/mock/simulation-config";

test("Journey 전체 동일 개념 지표·Audience·단계 진단은 A/B × 7/14/30일에서 일치한다",async()=>{for(const advertiserId of ["brand-a","brand-b"])for(const period of [7,14,30] as const){const query={advertiserId,period};const [h,f,b,r]=await Promise.all([getDashboard(query),loadFunnelWorkspace(query),loadPerformanceBaseline(query),loadExecutiveReport(query)]);assert.equal(h.totals.purchases,f.totals.purchases);assert.equal(h.totals.purchases,b.totalPurchases);assert.deepEqual(r.dashboard.totals,h.totals);assert.equal(f.totals.revenue,b.revenue);assert.equal(f.totals.spend,b.adSpend);assert.equal(f.totals.cpa,b.cpa);assert.equal(f.totals.roas,b.roas);assert.equal(f.totals.audience,b.currentAudience);assert.equal(f.totals.recovered,b.metaPurchases);const direct=diagnose(b).slice(0,4);direct.forEach((d,i)=>assert.equal(d.currentRate,f.stages[i+1].conversionRate));const first=diagnose(b).slice().sort((a,b)=>a.currentRate!/a.benchmark-b.currentRate!/b.benchmark)[0];assert.equal(getRecommendations(b,simulate(b,zeroLevers))[0].id,"improve-"+first.id);}});

test("추천에서 초안으로 광고주·세그먼트·Window·Channel·예산·원본 Scenario/Forecast를 보존한다",async()=>{for(const advertiserId of ["brand-a","brand-b"]){const ctx=await loadCampaignWorkspace({advertiserId,period:30}),levers=scenarios[1].levers,p=simulate(ctx.baseline,levers);for(const recommendation of getRecommendations(ctx.baseline,p)){const handoff=performanceHandoff(ctx.baseline,levers,recommendation),draft=newCampaignDraft(ctx,handoff.origin,handoff.sourceIds),e=evaluateCampaign(draft,ctx);assert.equal(draft.advertiserId,advertiserId);assert.equal(draft.window,handoff.origin.window);assert.equal(draft.segmentId,handoff.origin.segmentId);assert.equal(draft.sourceChannelId,handoff.sourceChannelId);assert.equal(draft.retargetingChannelId,handoff.retargetingChannelId);assert.equal(draft.origin.scenario,"recommended");assert.deepEqual(draft.origin.forecast,p);const segment=ctx.funnel.segments.find(s=>s.id===draft.segmentId)!;assert.equal(e.audience,segment.volume);assert.equal(draft.budget.daily,Math.round(ctx.baseline.retargetingSpend/30*(1+handoff.origin.recommendedBudgetChange/100)*segment.volume/ctx.baseline.currentAudience));}}});

test("Campaign → Operations → Reports는 Window·예산·상태 변경 이후 최신 상태와 이력을 표시한다",async()=>{const ctx=await loadCampaignWorkspace({advertiserId:"brand-a",period:30});const d=newCampaignDraft(ctx,{from:"Campaign Studio",segmentId:"cart-14d",window:14,recommendedBudgetChange:0,createdAt:new Date().toISOString()});const saved=saveCampaign(d,evaluateCampaign(d,ctx),ctx.advertiser.name,true);changeCampaignStatus("brand-a",saved.id,"MOCK ACTIVE");for(const action of [{type:"Window Change" as const,value:7},{type:"Decrease Budget" as const,value:10},{type:"Pause" as const,value:0}]){const rule={priority:1 as const,id:crypto.randomUUID(),advertiserId:"brand-a",campaignId:saved.id,name:action.type,enabled:true,createdAt:new Date().toISOString(),conditions:[{metric:"spend" as const,operator:">=" as const,value:0}],action};saveAutomationRule(rule);saveConflictResolution("brand-a",saved.id,"Higher Priority Wins");const ops=await loadOperations("brand-a",30),rec=ops.recommendations.find(r=>r.rule.id===rule.id)!;const change=await applyOperation("brand-a",rec,30);saveAutomationRule({...rule,enabled:false},true);const report=await loadExecutiveReport({advertiserId:"brand-a",period:30}),row=report.operations.campaigns.find(c=>c.campaign.id===saved.id)!;assert.deepEqual(row.campaign,change.after);assert.ok(report.operations.store.history.some(h=>h.id===change.id));assert.equal(report.dashboard.totals.purchases,ctx.baseline.totalPurchases);assert.equal(row.campaign.audienceSize,evaluateCampaign(row.campaign,ctx).audience);}const report=await loadExecutiveReport({advertiserId:"brand-a",period:30});assert.equal(report.counts.active,0);});
