"use client";
import {ConnectionWorkspace} from "@/features/platform/connection-workspace";
import {useUserRole} from "@/context/user-role-context";
import {can} from "@/lib/permissions";
import { useEffect,useRef,useState } from "react";
import {GA4ConnectionControls} from "@/features/ga4/connection-controls";
import {useGA4} from "@/features/ga4/provider";
import { getConnections } from "@/lib/connections";
import type { ConnectionReadiness } from "@/types/mvp";
import { DataState } from "@/components/data-state";
import { DataBackup } from "./data-backup";
import { AppSettings } from "./app-settings";
import "./mvp.css";
function ConnectionReadinessCenter(){const ga4=useGA4(),{user}=useUserRole();const data=getConnections(),[selected,setSelected]=useState<ConnectionReadiness|null>(null),[filter,setFilter]=useState("ALL"),items=data.connectors.filter(c=>filter==="ALL"||c.status===filter);return <div className="mvp"><div className="mvp-heading"><div><h2>데이터 연결</h2><p>데이터 수집부터 광고 실행까지, IntentBridge에 필요한 연결 상태를 관리합니다.</p></div></div><section className="mvp-readiness"><div><span className="mvp-eyebrow">ARCHITECTURE READINESS · NOT LIVE CONNECTIVITY</span><h2>API Integration Readiness</h2><p>전체 채널 카탈로그 기준입니다. 점수는 준비된 코드·Schema의 비중이며 실제 연결 성공률이 아닙니다.</p></div><strong data-testid="readiness-score">{data.overall}<small>%</small></strong></section><div className="mvp-heading"><h2>Connector 목록</h2><label>Connection Status<select value={filter} onChange={e=>setFilter(e.target.value)}>{["ALL","MOCK CONNECTED","NOT CONNECTED","READY FOR API","COMING SOON","REQUIRES SETUP"].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="mvp-scroll"><table><thead><tr>{["Connector / Category","Purpose","Status / Permission","Last Sync","Readiness"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(c=><tr key={c.id}><th><button className="mvp-link" onClick={()=>setSelected(c)}>{c.name}</button><small>{c.category}</small></th><td>{c.purpose}</td><td><span className="mvp-badge">{c.id==="ga4"?`${ga4.mode==="mock"?"MOCK CONNECTED · ":""}${ga4.data?.connection.status??"확인 중"}`:c.status}</span><small>{c.permission}</small></td><td>{c.lastSync}</td><td><b>{c.score}%</b><small>{c.readiness}</small></td></tr>)}</tbody></table></div>{!items.length&&<DataState kind="empty" message="이 상태에 해당하는 Connector가 없습니다. 실제 API 준비 완료로 표시된 연결은 아직 없습니다."/>}<section><h2>Connection Dependency Map</h2><div className="mvp-scroll"><table><thead><tr><th>Connector</th><th>사용 화면 / 기능</th><th>남은 구현</th></tr></thead><tbody>{data.connectors.map(c=><tr key={c.id}><th>{c.name}</th><td>{c.usedBy.join(" → ")}</td><td>{c.remaining.join(" · ")}</td></tr>)}</tbody></table></div></section><section><h2>API Readiness Checklist</h2><p>Mock UI/읽기 계약의 준비와 실제 연동 구현을 구분합니다. 미구현 항목을 임의로 체크할 수 없습니다.</p><div className="mvp-checklist">{data.checklist.map(c=><div key={c.label}><b>{c.ready?"✓":"○"} {c.label}</b><span>{c.note}</span></div>)}</div><p>GA4는 제한적 timeout/retry/cache가 구현되어 있습니다. 다른 채널은 타입·정책 준비 단계입니다.</p></section>{can(user.role,"MANAGE_SETTINGS")&&<><AppSettings/><DataBackup/></>}{selected&&<ConnectionDetail data={selected} close={()=>setSelected(null)}/>}</div>;}
function ConnectionDetail({data:c,close}:{data:ConnectionReadiness;close:()=>void}){const ga4=useGA4(),{user}=useUserRole();const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement;ref.current?.showModal();return()=>{if(previous instanceof HTMLElement)previous.focus();};},[]);return <dialog className="mvp mvp-dialog" ref={ref} aria-labelledby="connector-title" onCancel={close}><button className="mvp-close" onClick={close}>닫기</button><span className="mvp-badge">{c.status}</span><h2 id="connector-title">{c.name}</h2>{c.id==="ga4"&&can(user.role,"MANAGE_CONNECTIONS")&&<GA4ConnectionControls key={ga4.query.advertiserId}/>}<h3>Connection Overview</h3><p>{c.notes}</p><div className="mvp-two"><div><h3>Required Credentials · 이름만 표시</h3><ul>{c.credentials.map(i=><li key={i}>{i}</li>)}</ul></div><div><h3>Required Permissions</h3><ul>{c.permissions.map(i=><li key={i}>{i}</li>)}</ul></div></div><h3>Available Data</h3><p>{c.data.join(" / ")}</p><h3>Used By</h3><p>{c.usedBy.join(" → ")}</p><h3>Readiness Checklist · {c.score}%</h3><div className="mvp-checklist">{c.checklist.map(i=><div key={i.id}><b>{i.ready?"✓":"○"} {i.label} <small>{i.ready?i.weight:0} / {i.weight}</small></b><span>{i.evidence}</span></div>)}</div><DataState kind={c.status==="COMING SOON"?"disconnected":"permission"} message="ACTION REQUIRED · Credential 입력은 서버 설정으로만 수행합니다. GA4 외 채널의 실제 API 테스트는 지원하지 않습니다."/></dialog>;}

export function ConnectionCenter(){return <><ConnectionWorkspace/><details className="platform-panel"><summary>Advanced · 연결 아키텍처 및 기존 설정</summary><ConnectionReadinessCenter/></details></>;}
