import {ArrowUpRight,ChartNoAxesCombined,Route,Users,SlidersHorizontal,FileChartColumn,LayoutDashboard} from 'lucide-react';
import {preview as d,formatNumber as n,formatMoney as money} from './demo';
export function DashboardPreview(){return <div className="pw-product" aria-label="IntentBridge 대시보드 데모 미리보기">
 <div className="pw-window"><span><i/><i/><i/></span><span>IntentBridge / Workspace</span><span className="pw-label">DEMO DATA</span></div>
 <div className="pw-product-body"><aside className="pw-preview-rail" aria-label="미리보기 화면 구성"><b>IB<span>WORKSPACE</span></b><span className="is-active"><LayoutDashboard size={14}/>대시보드</span><span><Route size={14}/>고객 여정</span><span><SlidersHorizontal size={14}/>성과 개선</span><span><Users size={14}/>캠페인</span><span><FileChartColumn size={14}/>보고서</span><small>브랜드 A · 데모</small></aside>
 <div className="pw-preview-main"><header><div><small>PERFORMANCE OVERVIEW</small><h2>지금, 구매로 이어지는 흐름</h2></div><span>최근 30일</span></header>
 <div className="pw-mini-kpis">{[['광고비',money(d.spend)],['구매',n(d.purchases)+'건'],['매출',money(d.revenue)],['ROAS',d.roas.toFixed(1)+'%']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <div className="pw-chart"><div><b>고객의 다음 행동</b><span>구매까지 이어진 고객 흐름</span></div><div className="pw-bars">{[['유입',d.users],['상품 조회',d.view],['장바구니',d.cart],['결제',d.checkout],['직접 구매',d.direct]].map(([label,value])=><div key={label}><b>{n(Number(value))}</b><span style={{height:18+Number(value)/d.users*75}}/><small>{label}</small></div>)}</div></div>
 <a className="pw-preview-action" href="#journey"><span className="pw-opportunity-dot"/><div><small>가장 큰 개선 기회</small><b>상품 조회 → 장바구니</b><span>{n(d.drop)}명의 다음 행동을 살펴보세요.</span></div><ArrowUpRight size={20}/></a>
 </div></div><div className="pw-preview-footer"><span>● 데모 데이터로 보는 운영 흐름</span><span>유입부터 구매까지, 한 화면에서</span></div></div>;}
export function JourneyPreview(){const stages=[['유입',d.users],['상품 확인',d.view],['장바구니',d.cart],['결제 시작',d.checkout],['직접 구매',d.direct]];return <div className="pw-journey" aria-label="고객 여정 데모"><div className="pw-panel-heading"><span>고객 여정 · 브랜드 A</span><span className="pw-label">DEMO DATA</span></div><ol>{stages.map(([label,value],i)=><li key={label}><div><span>{label}</span><strong>{n(Number(value))}<small>명</small></strong></div><div className="pw-stage-track"><span style={{width:`${Math.max(10,Number(value)/d.users*100)}%`}}/></div>{i<4&&<small>↓ 다음 행동으로</small>}</li>)}</ol><div className="pw-recovery"><div><span>직접 구매하지 않은 고객</span><b>{n(d.users-d.direct)}명</b></div><span aria-hidden="true">→</span><div><span>재공략 가능 고객</span><b>{n(d.eligible)}명</b></div><span aria-hidden="true">→</span><div><span>재방문 추가 구매</span><b>+{n(d.recovered)}건</b></div></div><footer>직접 구매 {d.direct} + 재방문 구매 {d.recovered}<strong>총 구매 {d.purchases}건</strong></footer></div>;}
export function AudiencePreview(){return <div className="pw-audience"><div className="pw-panel-heading"><span>고객 그룹 → 캠페인 설계</span><span className="pw-label">DEMO DATA</span></div><small>선택한 고객 그룹</small><h3>장바구니에 담았지만<br/>구매하지 않은 고객</h3><div className="pw-audience-count">{n(d.cartAudience)}<span>명 · 최근 14일</span></div><p className="pw-excluded">✓ 최근 구매 고객 제외</p><div className="pw-campaign-line"><span>재공략 채널</span><b>Meta <small>DEMO CONNECTION</small></b></div><blockquote>“장바구니에 담아둔 상품이 있어요.<br/>배송과 혜택을 다시 확인해보세요.”</blockquote><div className="pw-campaign-line"><span>다음 단계</span><b>예산 설정 → 예상 성과 → 초안 저장</b></div><p className="pw-panel-note">캠페인 설계 예시입니다. 실제 광고는 집행하지 않습니다.</p></div>;}
export function ForecastPreview(){return <div className="pw-forecast"><div className="pw-panel-heading"><span><ChartNoAxesCombined size={18}/> 성과 개선 시뮬레이션</span><span className="pw-label pw-violet">DEMO FORECAST</span></div><p>구매·매출 20% 개선 가정</p><div className="pw-forecast-columns"><div><small>현재 구매</small><strong>{d.purchases}<span>건</span></strong><div className="pw-forecast-bar"/><small>{money(d.revenue)}</small></div><span aria-hidden="true">→</span><div><small>개선 후 예상 구매</small><strong>{d.forecastPurchases}<span>건</span></strong><div className="pw-forecast-bar projected"/><small>{money(d.forecastRevenue)}</small></div></div><footer>예상 구매 변화 <b>+{d.forecastPurchases-d.purchases}건</b></footer><p className="pw-panel-note">가정을 설명하기 위한 예시이며 실제 성과를 보장하지 않습니다. 플랫폼에서는 선택한 조건으로 예상 성과를 계산합니다.</p></div>;}
