import type {Metadata} from 'next';
import {ArrowRight} from 'lucide-react';
import {PublicSession,EntryLink} from '@/features/public/public-session';
import {DashboardPreview,JourneyPreview,AudiencePreview,ForecastPreview} from '@/features/public/product-preview';
import '@/features/public/public.css';
import {preview as d,formatNumber as n} from '@/features/public/demo';
export const dynamic='force-dynamic';
const origin=new URL(process.env.AUTH_URL||'http://localhost:3000').origin;
const title='IntentBridge | 광고 유입을 구매까지 연결합니다';
const description='광고 유입부터 고객 행동, 이탈과 재공략까지. IntentBridge에서 고객 여정을 분석하고 개선 캠페인과 예상 성과를 하나의 운영 흐름으로 확인하세요.';
export const metadata:Metadata={metadataBase:new URL(origin),title,description,alternates:{canonical:'/'},openGraph:{type:'website',locale:'ko_KR',siteName:'IntentBridge',title,description,url:'/'},robots:{index:true,follow:true}};
const nav=[['#product','제품'],['#how-it-works','작동 방식'],['#features','주요 기능'],['#use-cases','활용 방법']];
export default function PublicHome(){return <PublicSession><div className="pw-site"><a className="pw-skip" href="#public-main">본문으로 이동</a>
 <header className="pw-header"><div className="pw-container"><a href="/" className="pw-logo" aria-label="IntentBridge 홈페이지"><span className="pw-symbol" aria-hidden="true"/>IntentBridge</a><nav className="pw-nav" aria-label="제품 소개">{nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav><div className="pw-header-actions"><EntryLink secondary/><EntryLink short/></div><details className="pw-mobile-menu"><summary>메뉴</summary><nav aria-label="모바일 제품 소개">{nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}<EntryLink secondary/></nav></details></div></header>
 <main id="public-main">
 <section className="pw-hero pw-container" aria-labelledby="hero-title"><div className="pw-hero-copy"><p className="pw-kicker">고객의 다음 행동을 읽는 워크스페이스</p><h1 id="hero-title">광고 유입을,<br/><em>구매까지</em> 연결합니다.</h1><p>지금 어디에서 고객을 놓치고 있나요?<br/>흐름을 읽고, 다시 만날 고객을 찾고,<br/>다음 캠페인을 결정하세요.</p><div className="pw-actions"><EntryLink/><a className="pw-text-link" href="#product">제품 살펴보기 <ArrowRight size={17}/></a></div></div><div className="pw-hero-product"><DashboardPreview/></div><div className="pw-hero-caption">관심에서 구매까지. 숫자 사이에 있는 기회를 발견합니다.</div></section>
 <section className="pw-story pw-container" id="product"><div className="pw-story-copy" id="how-it-works"><p className="pw-kicker">하나의 여정을 따라가 봅니다</p><h2>들어온 고객은 많습니다.<br/>어디에서 멈췄을까요?</h2><p>이 화면은 공개된 예시 데이터입니다.<br/>실제 광고주의 정보나 광고 계정에 연결하지 않습니다.</p><div className="pw-story-loss"><strong>{n(d.drop)}</strong><span>명이 상품을 확인한 뒤<br/>장바구니까지 이어지지 않았습니다.</span></div><p>모든 이탈 고객이 재공략 대상은 아닙니다. 행동과 기간을 확인하고, 구매 고객을 제외해 다음 캠페인을 설계합니다.</p><a className="pw-text-link" href="#audience">이탈에서 다음 행동으로 <ArrowRight size={17}/></a></div><div id="journey"><JourneyPreview/></div></section>
 <section className="pw-experience pw-container" id="features"><header><p className="pw-kicker">판단이 실행으로 이어지는 곳</p><h2>다시 만날 고객을 정하고,<br/>그다음의 변화를 비교합니다.</h2></header><div className="pw-experience-row" id="audience"><div><h3>고객 그룹에서 캠페인으로</h3><p>장바구니에 남은 관심을 광고의 다음 문장으로 옮깁니다. 고객, 채널, 메시지, 예산을 한 흐름에서 검토하세요.</p><p>현재 플랫폼의 광고 연결과 집행은 데모 환경입니다.</p></div><AudiencePreview/></div><div className="pw-experience-row" id="forecast"><div><h3>현재에서 예상으로</h3><p>개선안을 적용하기 전에 어떤 변화가 가능한지 살펴봅니다. 예상값은 실적과 구분하고, 조건을 바꾸며 비교합니다.</p></div><ForecastPreview/></div><div className="pw-capability-index"><span>함께 사용하는 도구</span><p>고객 여정 · 고객 그룹 · 캠페인 초안 · 운영 제안 · 광고주 보고서</p></div></section>
 <section className="pw-agency pw-container" id="use-cases"><div><p className="pw-kicker">같은 흐름, 각자의 시야</p><h2>여러 광고주와 담당자가<br/>하나의 맥락을 공유합니다.</h2><p>운영자는 전체 우선순위를, 마케터는 담당 광고주의 다음 액션을, 광고주는 성과와 개선 방향을 확인합니다.</p></div><ol className="pw-role-flow"><li><span>전체 운영</span><h3>누구에게 집중할지 정합니다.</h3><p>광고주와 담당자를 연결하고 전체 현황을 확인합니다.</p></li><li><span>담당 마케터</span><h3>흐름을 읽고 실행을 준비합니다.</h3><p>담당 광고주의 개선안과 캠페인 초안을 검토합니다.</p></li><li><span>광고주 공유</span><h3>결과와 다음 방향을 이해합니다.</h3><p>허용된 워크스페이스의 성과와 보고서를 확인합니다.</p></li></ol><div className="pw-channel-support" id="channels"><h3>유입 채널이 달라도,<br/>고객 여정은 하나로 연결됩니다.</h3><p>ChatGPT · Naver · Meta · Google · Kakao · Daangn</p><small>현재 분석 예시는 GPT → Meta입니다. 7개 매체의 연결 UX는 데모로 제공하며, 다른 매체 실적 연동과 ChatGPT Ads는 준비 예정입니다.</small></div></section>
 <section className="pw-final-cta"><div className="pw-container"><h2>오늘 놓친 고객에게,<br/>다음 행동을 제안하세요.</h2><div className="pw-actions"><EntryLink/><EntryLink secondary/></div><p>회원가입 후 관리자 승인과 광고주 연결을 거쳐 시작합니다.</p></div></section>
 </main><footer className="pw-footer"><div className="pw-container"><a href="/" className="pw-logo"><span className="pw-symbol" aria-hidden="true"/>IntentBridge</a><p>관심에서 구매까지, 하나의 흐름으로.</p><div><a href="#product">제품</a><a href="#channels">데모 안내</a><a href="/login">로그인</a><a href="/signup">회원가입</a></div><small>© IntentBridge</small></div></footer>
 </div></PublicSession>;}
