import type {Metadata} from 'next';
import {ArrowRight,Route,ScanSearch,Users,SlidersHorizontal,Megaphone,FileChartColumn,Check} from 'lucide-react';
import {PublicSession,EntryLink} from '@/features/public/public-session';
import {DashboardPreview,JourneyPreview,AudiencePreview,ForecastPreview} from '@/features/public/product-preview';
import '@/features/public/public.css';
export const dynamic='force-dynamic';
const origin=new URL(process.env.AUTH_URL||'http://localhost:3000').origin;
const title='IntentBridge | 광고 유입을 구매까지 연결합니다';
const description='광고 유입부터 고객 행동, 이탈과 재공략까지. IntentBridge에서 고객 여정을 분석하고 개선 캠페인과 예상 성과를 하나의 운영 흐름으로 확인하세요.';
export const metadata:Metadata={metadataBase:new URL(origin),title,description,alternates:{canonical:'/'},openGraph:{type:'website',locale:'ko_KR',siteName:'IntentBridge',title,description,url:'/'},robots:{index:true,follow:true}};
const nav=[['#product','제품'],['#how-it-works','작동 방식'],['#features','주요 기능'],['#use-cases','활용 방법']];
export default function PublicHome(){return <PublicSession><div className="pw-site"><a className="pw-skip" href="#public-main">본문으로 이동</a>
 <header className="pw-header"><div className="pw-container"><a href="/" className="pw-logo" aria-label="IntentBridge 홈페이지"><span className="pw-symbol" aria-hidden="true"/>IntentBridge</a><nav className="pw-nav" aria-label="제품 소개">{nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav><div className="pw-header-actions"><EntryLink secondary/><EntryLink short/></div><details className="pw-mobile-menu"><summary>메뉴</summary><nav aria-label="모바일 제품 소개">{nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}<EntryLink secondary/></nav></details></div></header>
 <main id="public-main">
 <section className="pw-hero pw-container" aria-labelledby="hero-title"><div className="pw-hero-copy"><span className="pw-eyebrow">FROM INTENT TO PURCHASE</span><h1 id="hero-title">광고 유입을,<br/><em>구매까지</em> 연결합니다.</h1><p>유입부터 고객 행동, 이탈, 재공략,<br className="pw-desktop-break"/>최종 구매까지 하나의 흐름으로 확인하세요.</p><div className="pw-actions"><EntryLink/><a className="pw-text-link" href="#product">제품 살펴보기 <ArrowRight size={17}/></a></div><div className="pw-hero-note"><span/>광고대행사와 마케터를 위한 운영 워크스페이스</div></div><div className="pw-hero-product"><DashboardPreview/></div><div className="pw-hero-caption"><span>데이터를 읽는 일에서, 다음 행동을 결정하는 일로.</span><span>01 — THE CONNECTED WORKSPACE</span></div></section>
 <section className="pw-flow-section" id="product"><div className="pw-container"><div className="pw-section-intro"><span className="pw-eyebrow">ONE CONNECTED JOURNEY</span><h2>클릭 이후를 봅니다.</h2><p>어디서 고객이 들어왔는지만 보는 것이 아니라,<br/>어디에서 이탈했고 어떤 고객을 다시 공략해야 하는지까지 연결합니다.</p></div><ol className="pw-flow">{[['01','유입','ChatGPT · Naver · Meta','Google · 기타 유입'],['02','행동','상품 조회 · 장바구니','결제 시작'],['03','이탈 발견','구매하지 않은','고관여 고객'],['04','재공략 → 구매','고객 그룹 · 캠페인 설계','재방문과 최종 구매']].map(([num,label,a,b])=><li key={num}><span>{num}</span><h3>{label}</h3><p>{a}<br/>{b}</p><ArrowRight size={20} aria-hidden="true"/></li>)}</ol><p className="pw-small">매체별 지원 범위는 아래 연결 상태에서 확인할 수 있습니다.</p></div></section>
 <section className="pw-container pw-section pw-problem"><div><span className="pw-eyebrow">A BETTER QUESTION</span><h2>유입 수보다 중요한 건,<br/>그 고객이 결국<br/><em>구매했는가.</em></h2></div><div><p className="pw-lead">광고 클릭은 발생했지만,<br/>구매로 이어지지 않은 고객이 있습니다.</p><p>광고 플랫폼의 클릭·전환 지표와 함께, 광고 이후 고객이 어떤 행동을 했고 어디에서 멈췄는지 살펴보세요.</p><ol className="pw-check-list">{['이탈 구간을 찾고','다시 만날 고객 그룹을 만들고','재공략 캠페인을 설계하고','최종 구매까지 확인합니다.'].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ol></div></section>
 <section className="pw-container pw-section" id="how-it-works"><div className="pw-section-intro"><span className="pw-eyebrow">HOW IT WORKS</span><h2>복잡한 분석 없이,<br/>3단계면 충분합니다.</h2></div><div className="pw-three-steps">{[['01','데이터를 연결하세요.','GA4와 광고 매체 데이터를 한 곳에서 확인합니다.','DEMO CONNECTION'],['02','놓친 고객을 찾으세요.','가장 큰 이탈 구간과 개선 기회를 확인합니다.','CUSTOMER JOURNEY'],['03','다시 구매로 연결하세요.','고객 그룹, 재공략 캠페인과 예상 성과를 설계합니다.','DEMO FORECAST']].map(([num,heading,copy,tag])=><article key={num}><span className="pw-step-number">{num}</span><h3>{heading}</h3><p>{copy}</p><small>{tag}</small></article>)}</div></section>
 <section className="pw-showcases"><div className="pw-container">
 <div className="pw-showcase-head"><span className="pw-eyebrow">INSIDE INTENTBRIDGE</span><h2>현재 성과를 보는 데서<br/>끝나지 않습니다.</h2><p>현재 성과 → 가장 큰 문제 → 개선 기회 → 다음 액션.<br/>분석과 실행 사이의 빈틈을 줄이는 하나의 워크스페이스입니다.</p></div>
 <section className="pw-showcase" id="journey"><div className="pw-showcase-copy"><span className="pw-eyebrow">01 / CUSTOMER JOURNEY</span><h2>어디에서 고객을<br/>놓쳤는지 확인하세요.</h2><p>상품을 살펴본 고객 중 누가 장바구니에 담았고, 누가 구매 직전에 멈췄을까요? 고객의 행동과 재방문 구매를 함께 확인합니다.</p><a href="#audience" className="pw-text-link">이탈 고객을 다음 캠페인으로 <ArrowRight size={17}/></a></div><JourneyPreview/></section>
 <section className="pw-showcase pw-reverse" id="audience"><div className="pw-showcase-copy"><span className="pw-eyebrow">02 / AUDIENCE & CAMPAIGN</span><h2>놓친 고객을<br/>다시 구매로 연결합니다.</h2><p>장바구니에 담았지만 구매하지 않은 고객. 다시 만날 고객을 선택하면 고객 그룹과 조건을 캠페인 설계로 이어갈 수 있습니다.</p><ul className="pw-inline-list"><li>고객 그룹 선택</li><li>구매 고객 제외</li><li>메시지·예산 설계</li></ul></div><AudiencePreview/></section>
 <section className="pw-showcase" id="forecast"><div className="pw-showcase-copy"><span className="pw-eyebrow">03 / PERFORMANCE LAB</span><h2>개선했을 때의 결과까지<br/>미리 확인합니다.</h2><p>전환율과 예산을 조정하며 현재 성과와 예상 결과를 비교하세요. 수치의 차이를 보고 다음에 시도할 개선안을 선택합니다.</p><span className="pw-forecast-note">예상 성과는 현재 실적과 구분해서 보여드립니다.</span></div><ForecastPreview/></section>
 </div></section>
 <section className="pw-container pw-section" id="channels"><div className="pw-section-intro"><span className="pw-eyebrow">BUILT FOR CROSS-MEDIA</span><h2>GPT만을 위한 구조가 아닙니다.</h2><p>유입 매체가 달라도 고객의 행동은 하나의 여정으로 이어집니다.</p></div><div className="pw-channels"><div><small>유입 채널</small><p>ChatGPT · Naver · Meta<br/>Google · Kakao · Daangn</p></div><span aria-hidden="true">→</span><div className="pw-channel-core"><span className="pw-symbol" aria-hidden="true"/><b>IntentBridge</b><small>고객 행동 · 이탈 · 재공략</small></div><span aria-hidden="true">→</span><div><small>재공략 채널</small><p>Meta · Naver · Google<br/>기타 재공략 채널</p></div></div><div className="pw-channel-status"><span><b>DEMO CONNECTION</b> 7개 매체의 연결 과정을 체험</span><span><b>DEMO DATA</b> 현재 분석 예시: GPT → Meta</span><span><b>PLANNED</b> 다른 매체 실적 연동 · ChatGPT Ads</span></div></section>
 <section className="pw-feature-section" id="features"><div className="pw-container"><div className="pw-section-intro"><span className="pw-eyebrow">FOCUS ON THE NEXT ACTION</span><h2>운영에 필요한 핵심만,<br/>서로 이어지도록.</h2></div><div className="pw-features">{[[Route,'고객 여정 분석','유입부터 최종 구매까지 고객의 행동을 연결합니다.'],[ScanSearch,'이탈 구간 발견','고객이 멈춘 지점과 먼저 확인할 기회를 찾습니다.'],[Users,'재공략 고객 그룹','행동과 기간을 기준으로 다시 만날 고객을 선택합니다.'],[SlidersHorizontal,'성과 개선 시뮬레이션','개선 조건에 따른 구매·매출의 예상 변화를 비교합니다.'],[Megaphone,'캠페인 설계','고객 그룹부터 메시지, 예산과 초안까지 이어갑니다.'],[FileChartColumn,'광고주 보고서','성과와 개선 현황을 읽기 쉬운 보고서로 정리합니다.']].map(([Icon,heading,copy])=>{const Symbol=Icon as typeof Route;return <article key={String(heading)}><Symbol size={24} strokeWidth={1.5}/><h3>{String(heading)}</h3><p>{String(copy)}</p></article>;})}</div></div></section>
 <section className="pw-container pw-section" id="use-cases"><div className="pw-agency-intro"><div><span className="pw-eyebrow">FOR AGENCY TEAMS</span><h2>여러 광고주를,<br/>하나의 운영 흐름으로.</h2></div><p>담당 광고주 전환부터 데이터 상태, 성과 이상징후,<br/>운영 액션과 보고서까지. 각자의 역할에 맞는 화면에서<br/>같은 고객 여정을 함께 봅니다.</p></div><div className="pw-roles">{[['광고대행사','전체 광고주 운영 관리','사용자와 담당자를 배정하고 전체 운영 현황을 확인합니다.','SUPER_ADMIN'],['마케터 / AE','담당 광고주 분석·운영','개선 기회를 찾고 캠페인·운영 액션을 검토합니다.','MANAGER'],['광고주','성과와 개선 현황 확인','어려운 설정 없이 성과와 앞으로의 개선 방향을 확인합니다.','ADVERTISER']].map(([title,heading,copy,role])=><article key={role}><span>{title}</span><h3>{heading}</h3><p>{copy}</p><small>{role}</small></article>)}</div></section>
 <section className="pw-final-cta"><div className="pw-container"><span className="pw-eyebrow">MAKE THE NEXT CONNECTION</span><h2>광고 유입 이후까지<br/>연결해보세요.</h2><div className="pw-actions"><EntryLink/><EntryLink secondary/></div><p>회원가입 후 관리자 승인과 광고주 연결을 거쳐 시작합니다.</p></div></section>
 </main><footer className="pw-footer"><div className="pw-container"><a href="/" className="pw-logo"><span className="pw-symbol" aria-hidden="true"/>IntentBridge</a><p>관심에서 구매까지, 하나의 흐름으로.</p><div><a href="#product">제품</a><a href="#channels">데모 안내</a><a href="/login">로그인</a><a href="/signup">회원가입</a></div><small>© IntentBridge</small></div></footer>
 </div></PublicSession>;}
