"use client";
import {useState,type ReactNode} from "react";
import Link from "next/link";
import {ArrowRight,Inbox} from "lucide-react";

export const compactMoney=(value:number)=>{const n=Math.abs(value),sign=value<0?"−":"";return `${sign}₩${n>=1e8?`${Number((n/1e8).toFixed(2)).toLocaleString("ko-KR")}억`:n>=1e4?`${Number((n/1e4).toFixed(1)).toLocaleString("ko-KR")}만`:Math.round(n).toLocaleString("ko-KR")}`;};
export function Money({value}:{value:number}){return <span title={`₩${Math.round(value).toLocaleString("ko-KR")}`}>{compactMoney(value)}</span>}
export function DataSourceBadge({kind="mock"}:{kind?:"mock"|"real"|"forecast"|"automation"}){return <span className={`ui-badge ui-source ${kind}`}>{({mock:"MOCK DATA",real:"REAL GA4 DATA",forecast:"DEMO FORECAST",automation:"MOCK AUTOMATION"})[kind]}</span>}
const statuses:Record<string,[string,string]>={HEALTHY:["정상","positive"],WATCH:["확인 필요","warning"],"ACTION REQUIRED":["조치 필요","critical"],LEARNING:["학습 중","neutral"],LIMITED:["제한됨","warning"],"MOCK ACTIVE":["운영 중 · Mock","positive"],ACTIVE:["운영 중","positive"],DRAFT:["초안","neutral"],READY:["준비 완료","neutral"],PAUSED:["일시 중지","warning"]};
export function StatusBadge({status}:{status:string}){const [label,tone]=statuses[status.toUpperCase()]??[status,"neutral"];return <span className={`ui-badge ${tone}`} title={status}>{label}</span>}
export function SectionHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="ui-section-header"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
export function KpiMetric({label,value,note,tone="neutral"}:{label:string;value:ReactNode;note?:string;tone?:"neutral"|"positive"|"warning"|"forecast"}){return <div className={`ui-metric ${tone}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export function InsightBanner({children,href}:{children:ReactNode;href?:string}){return <div className="ui-insight"><span className="ui-insight-label">개선 기회</span><p>{children}</p>{href&&<Link href={href}>자세히 보기 <ArrowRight size={14}/></Link>}</div>}
export function EmptyState({title,description,href,action}:{title:string;description:string;href?:string;action?:string}){return <div className="ui-empty"><Inbox size={22}/><div><h3>{title}</h3><p>{description}</p>{href&&<Link className="ui-secondary" href={href}>{action??"자세히 보기"} <ArrowRight size={14}/></Link>}</div></div>}
export function WorkspaceSkeleton(){return <div className="ui-skeleton" role="status" aria-label="성과를 불러오는 중"><div className="ux-kpis">{[0,1,2,3].map(i=><div key={i}/>)}</div><div/><span className="sr-only">성과를 불러오는 중…</span></div>}
export function DataTable({label,children}:{label:string;children:ReactNode}){return <div className="ui-table ux-table" role="region" aria-label={label} tabIndex={0}><table>{children}</table></div>}
export function ActionQueue({items}:{items:{id:string;title:string;description:string;status:string;href:string;action:string}[]}){return <ol className="ui-action-queue">{items.map((item,index)=><li key={item.id}><span className="ui-priority">P{index+1}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><StatusBadge status={item.status}/><Link className="ui-secondary" href={item.href}>{item.action}<ArrowRight size={14}/></Link></li>)}</ol>}
export function TrendChart({rows,title,description,unit="건",forecast=false}:{rows:{date:string;value:number}[];title:string;description:string;unit?:string;forecast?:boolean}){
 const [active,setActive]=useState<number|null>(null),max=Math.max(1,...rows.map(r=>r.value)),last=rows.length-1,index=active===null?last:Math.min(active,last),selected=rows[index];
 const x=(i:number)=>40+i*640/Math.max(1,last),y=(v:number)=>162-v/max*132,points=rows.map((r,i)=>`${x(i)},${y(r.value)}`).join(" ");
 return <section className={`ui-chart-panel ${forecast?"forecast":""}`}><SectionHeader title={title} description={description}/>{!rows.length?<EmptyState title="아직 추이 데이터가 없습니다." description="조회 기간을 변경해 주세요."/>:<><div className="ui-chart-readout" aria-live="polite"><span>{selected.date}</span><strong>{selected.value.toLocaleString("ko-KR")}{unit}</strong><small>차트에 마우스를 올리거나 좌우 방향키로 확인</small></div><svg viewBox="0 0 720 190" role="img" aria-label={title} tabIndex={0} onKeyDown={e=>{if(["ArrowLeft","ArrowRight","Home","End"].includes(e.key)){e.preventDefault();setActive(e.key==="Home"?0:e.key==="End"?last:Math.max(0,Math.min(last,index+(e.key==="ArrowRight"?1:-1))));}}} onPointerMove={e=>{const rect=e.currentTarget.getBoundingClientRect();setActive(Math.max(0,Math.min(last,Math.round((((e.clientX-rect.left)/rect.width)*720-40)/640*last))));}} onPointerLeave={()=>setActive(null)}><title>{title}。{description}</title>{[0,.5,1].map(t=><g key={t}><line x1="40" x2="680" y1={y(max*t)} y2={y(max*t)} stroke="var(--ui-line)" strokeDasharray="3 5"/><text x="2" y={y(max*t)+4} fill="var(--ui-muted)" fontSize="12">{Math.round(max*t)}</text></g>)}<polygon points={`40,162 ${points} ${x(last)},162`} fill="currentColor" opacity=".07"/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2.5"/><line x1={x(index)} x2={x(index)} y1="22" y2="162" stroke="currentColor" strokeDasharray="3 3" opacity=".4"/><circle cx={x(index)} cy={y(selected.value)} r="4" fill="currentColor"/><text x="40" y="184" fontSize="12" fill="var(--ui-muted)">{rows[0].date}</text><text x="680" y="184" textAnchor="end" fontSize="12" fill="var(--ui-muted)">{rows[last].date}</text></svg><details><summary>일별 수치 보기</summary><DataTable label={title+" 일별 수치"}><thead><tr><th>날짜</th><th>수치</th></tr></thead><tbody>{rows.map(r=><tr key={r.date}><th>{r.date}</th><td>{r.value.toLocaleString("ko-KR")}{unit}</td></tr>)}</tbody></DataTable></details></>}</section>;
}
export function ForecastComparison({current,forecast,label,unit="건",money=false}:{current:number;forecast:number;label:string;unit?:string;money?:boolean}){const format=(v:number)=>money?compactMoney(v):`${v.toLocaleString("ko-KR")}${unit}`,max=Math.max(1,current,forecast);return <div className="ui-forecast-comparison"><span>{label}</span><div><span>현재</span><b title={String(current)}>{format(current)}</b><i style={{width:`${current/max*100}%`}}/></div><div className="forecast"><span>개선 후 예상</span><b title={String(forecast)}>{format(forecast)}</b><i style={{width:`${forecast/max*100}%`}}/></div><strong>{forecast-current>=0?"+":""}{format(forecast-current)}</strong></div>}
