import type { ConnectionDefinition, ConnectionReadiness, ReadinessItem } from "../types/mvp";
const criteria=[{id:"interface",label:"Connector Interface",weight:20},{id:"mock",label:"Mock Adapter",weight:15},{id:"service",label:"Service Layer",weight:15},{id:"types",label:"Type 계약",weight:10},{id:"env",label:"Environment Schema",weight:10},{id:"errors",label:"실제 Connector Error Handling",weight:10},{id:"credentials",label:"실제 Credential 검증",weight:10},{id:"integration",label:"실제 Integration Test",weight:10}];
function checklist(level:"mock"|"traffic"|"planned"):ReadinessItem[]{const ready=level==="mock"?["interface","mock","service","types","env"]:level==="traffic"?["mock","service","types","env"]:["types"];return criteria.map(c=>({...c,ready:ready.includes(c.id),evidence:ready.includes(c.id)?c.id==="interface"?"lib/connectors/interfaces.ts · 기존 읽기 계약":c.id==="mock"?"lib/connectors/mock.ts / funnel.ts · 합성 데이터":c.id==="service"?"dashboard / funnel / simulation Service":c.id==="types"?"types/domain.ts · funnel.ts · campaign.ts":".env.example · 빈 변수 이름만 준비":c.id==="errors"?"base.ts에 오류·timeout·retry 타입만 있음; 실제 처리 미구현":c.id==="credentials"?"실제 값 입력·저장·검증하지 않음":c.id==="integration"?"Mock 테스트만 있음; 실제 통합 검증 미실행":"채널 카탈로그만 준비; 전용 계약/Adapter 미구현"}));}
const definitions:ConnectionDefinition[]=[
 {id:"ga4",name:"Google Analytics 4",category:"Analytics",purpose:"Traffic / Funnel / Revenue",status:"MOCK CONNECTED",permission:"Viewer (계획)",lastSync:"로컬 Mock · 외부 Sync 없음",credentials:["Property ID","서버 Service Account JSON 파일 경로","GA4 Data API 사용 설정"],permissions:["Property 읽기 권한 검토"],data:["유입·세션","행동 이벤트","직접 구매·매출"],usedBy:["Overview","Funnel","Performance Lab","Reports"],checklist:checklist("mock").map(i=>i.id==="errors"?{...i,ready:true,evidence:"GA4 서버 오류 분류·제한적 retry·timeout·캐시 구현"}:i.id==="env"?{...i,evidence:"GOOGLE_APPLICATION_CREDENTIALS 서버 파일 경로 / GA4_PROPERTY_MAP"}:i),notes:"MockAnalyticsConnector를 유지하며 GA4Connector와 공식 Data API SDK 읽기 Adapter를 추가했습니다. 실제 Credential·Property 검증은 연결 테스트 전까지 미완료입니다."},
 {id:"meta-pixel",name:"Meta Pixel / Dataset",category:"Behavior & Audience",purpose:"Site Behavior / Audience",status:"MOCK CONNECTED",permission:"Dataset 접근 권한 (미검증)",lastSync:"로컬 Mock · 외부 Sync 없음",credentials:["Pixel / Dataset ID","Business 자산 연결","이벤트 동의·중복 제거 설계"],permissions:["Dataset 권한 검토"],data:["ViewContent / AddToCart / BeginCheckout","Purchase 제외","재공략 가능 고객"],usedBy:["Funnel","Audience","Campaign Studio"],checklist:checklist("mock"),notes:"MockRetargetingConnector / MockFunnelConnector로 합성 코호트를 제공합니다. 실제 Pixel/CAPI 수집 코드는 없습니다."},
 {id:"meta-marketing",name:"Meta Marketing API",category:"Advertising",purpose:"Campaign / Spend / Operations",status:"MOCK CONNECTED",permission:"Ad Account 읽기·쓰기 (미검증)",lastSync:"로컬 Mock · 외부 Sync 없음",credentials:["System User 생성","Ad Account ID","Dataset ID","Access Token","Business 검증","Integration Test"],permissions:["최소 읽기 권한 검증 후 쓰기 권한 별도 승인"],data:["광고비 Mock","Campaign 설계안","Mock 운영 상태"],usedBy:["Campaign Studio","Operations","Reports"],checklist:checklist("mock"),notes:"AdsConnector는 읽기 Mock 계약입니다. 실제 Campaign 생성·변경용 쓰기 Adapter는 아직 없습니다."},
 {id:"chatgpt-ads",name:"ChatGPT Ads",category:"Source / Attribution",purpose:"Paid Traffic / Campaign Attribution",status:"MOCK CONNECTED",permission:"제공 범위 확인 전",lastSync:"유입 Mock · 외부 Sync 없음",credentials:["실제 API 제공 여부·이용 자격 확인","공식 인증 방식 확인","Account ID (가칭)","API Key (가칭)","Integration Test"],permissions:["실제 지원 권한 확인 필요"],data:["GPT Organic / GPT Ads 유입 Mock"],usedBy:["Traffic Source","Funnel","Campaign Attribution"],checklist:checklist("traffic"),notes:"유입 집계 Mock만 존재합니다. 실제 광고 API의 가용성·계약·인증 방식을 확인한 상태가 아닙니다."},
 ...[{id:"naver",name:"Naver"},{id:"google-ads",name:"Google Ads"},{id:"kakao",name:"Kakao"},{id:"youtube",name:"YouTube / Google"},{id:"crm",name:"CRM / Other"}].map(c=>({...c,category:"Future Channel",purpose:"추가 유입 / 재공략 확장",status:"COMING SOON" as const,permission:"미정 · 제공사별 검토",lastSync:"없음",credentials:["API 제공 범위 확인","계정·권한 설계","전용 Adapter","Integration Test"],permissions:["최소 권한 정책 설계"],data:["지원 데이터 계약 정의 예정"],usedBy:["Traffic Source","Campaign Studio"],checklist:checklist("planned"),notes:"선택 UI와 공통 채널 타입만 있으며 실제 데이터 Adapter는 없습니다."})),
];
export function connectionReadiness(c:ConnectionDefinition):ConnectionReadiness {const score=c.checklist.reduce((sum,item)=>sum+(item.ready?item.weight:0),0);return {...c,score,readiness:c.checklist.every(i=>i.ready)?"READY":"ACTION REQUIRED",remaining:c.checklist.filter(i=>!i.ready).map(i=>i.label)};}
export function getConnections(){const connectors=definitions.map(connectionReadiness);return {connectors,overall:Math.round(connectors.reduce((sum,c)=>sum+c.score,0)/connectors.length),checklist:[{label:"Connector Interface",ready:true,note:"기존 Mock 읽기 계약; 매체별 실제 Adapter는 별도 필요"},{label:"Service Layer",ready:true,note:"UI / 계산 / Connector 분리"},{label:"Environment Schema",ready:true,note:".env.example · 이름만 존재"},{label:"Error Handling",ready:true,note:"Mock 오류와 공통 Error UI; 실제 Connector 오류 처리 제외"},{label:"Loading State",ready:true,note:"공통 상태 UI와 기존 로딩 처리"},{label:"Permission Handling",ready:false,note:"표시 Component만 준비; 실제 권한 확인 미구현"},{label:"Credential Validation",ready:false,note:"입력·검증하지 않음"},{label:"Integration Test",ready:false,note:"Mock 테스트만 수행"},{label:"Rate Limit Handling",ready:true,note:"GA4 읽기만 제한 재시도; 다른 채널 미구현"},{label:"Retry Strategy",ready:true,note:"GA4 일시 오류 최대 2회 재시도; 다른 채널 미구현"}]};}
