"use client";
import {useEffect,useRef,useState} from "react";
import {getSession,signIn} from "next-auth/react";
import {Mail} from "lucide-react";
import {AuthFrame} from "@/components/auth/auth-frame";
type State="checking"|"check-error"|"idle"|"sending"|"sent"|"error";
function maskedEmail(value:string){const [name,domain]=value.split("@");return domain?name.slice(0,Math.min(3,Math.max(1,name.length-1)))+"***@"+domain:"";}
export default function Login(){
 const [email,setEmail]=useState(""),[state,setState]=useState<State>("checking"),[message,setMessage]=useState(""),[invalid,setInvalid]=useState(false),[check,setCheck]=useState(0);
 const lock=useRef(false),input=useRef<HTMLInputElement>(null),sentHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let active=true;setState("checking");getSession().then(session=>{if(!active)return;if(session?.user){window.location.replace("/");return;}const params=new URLSearchParams(window.location.search);if(params.has("error")){setMessage("로그인 링크가 만료되었거나 사용할 수 없습니다. 새 링크를 요청해 주세요.");setState("error");}else setState(params.has("sent")?"sent":"idle");}).catch(()=>{if(active)setState("check-error")});return()=>{active=false}},[check]);
 useEffect(()=>{if(state==="sent")sentHeading.current?.focus()},[state]);
 const otherEmail=()=>{setEmail("");setInvalid(false);setMessage("");setState("idle");window.history.replaceState(null,"","/login");requestAnimationFrame(()=>input.current?.focus())};
 return <AuthFrame>{state==="checking"?<div className="auth-loading-inline" role="status"><span className="auth-dot" aria-hidden="true"/>로그인 상태 확인 중...</div>:state==="check-error"?<><h2>로그인 상태를 확인하지 못했습니다.</h2><p role="status">연결 상태를 확인한 뒤 다시 시도해주세요.</p><button className="auth-primary" onClick={()=>setCheck(v=>v+1)}>다시 시도</button></>:state==="sent"?<><span className="auth-state-icon" aria-hidden="true"><Mail size={24}/></span><h2 ref={sentHeading} tabIndex={-1}>메일함을 확인해주세요.</h2><div role="status"><p>로그인 링크를 보냈습니다.{email&&<><br/><span className="auth-recipient">{maskedEmail(email)}</span></>}</p></div><p>전송된 링크는 15분 후 만료됩니다.<br/>메일이 보이지 않으면 스팸함도 확인해주세요.</p><button className="auth-secondary" onClick={otherEmail}>다른 이메일 사용</button></>:<><h2>워크스페이스 로그인</h2><p>업무용 이메일로 로그인하세요.</p><form className="auth-form" noValidate onSubmit={async e=>{e.preventDefault();if(lock.current)return;if(!input.current?.validity.valid){setInvalid(true);setMessage("올바른 이메일 주소를 입력해주세요.");setState("error");input.current?.focus();return;}lock.current=true;setInvalid(false);setMessage("");setState("sending");try{const result=await signIn("resend",{email:email.trim(),redirect:false,redirectTo:"/"});if(result?.error){setMessage("로그인 링크를 보내지 못했습니다. 잠시 후 다시 시도해주세요.");setState("error");return;}setState("sent");}catch{setMessage("로그인 링크를 보내지 못했습니다. 잠시 후 다시 시도해주세요.");setState("error");}finally{lock.current=false;}}} aria-busy={state==="sending"}><label htmlFor="login-email">이메일</label><div className="auth-input-row"><input ref={input} id="login-email" name="email" type="email" autoComplete="email" autoCapitalize="none" spellCheck={false} placeholder="name@company.com" maxLength={254} required readOnly={state==="sending"} value={email} aria-invalid={invalid} aria-describedby={message?"login-message login-help":"login-help"} onChange={e=>{setEmail(e.target.value);if(invalid){setInvalid(false);setMessage("");setState("idle")}}}/><button className="auth-primary" disabled={state==="sending"}>{state==="sending"?"로그인 링크 보내는 중...":state==="error"&&!invalid?"다시 시도":"로그인 링크 받기"}</button></div><p id="login-message" className="auth-error" role="status" aria-live="polite">{message}</p><p id="login-help" className="auth-help">비밀번호 없이 이메일로 전송되는 안전한 로그인 링크를 사용합니다.</p></form></>}</AuthFrame>;
}
