"use client";
import {useEffect,useState,useRef} from "react";
import Link from "next/link";
import {flushServerStorage} from "@/lib/server-storage";
type Workspace={id:string;name:string;industry:string;productName:string;status:string};
type User={id:string;name:string|null;email:string;role:string;status:string;createdAt:string;lastLoginAt:string|null;members:{advertiserId:string}[]};
const pendingRequests=new Map<string,string>();
async function api(path:string,method="GET",body?:unknown){const fingerprint=JSON.stringify([path,method,body]);if(body&&!pendingRequests.has(fingerprint)){if(pendingRequests.size>=100)pendingRequests.delete(pendingRequests.keys().next().value!);pendingRequests.set(fingerprint,crypto.randomUUID())}const response=await fetch(path,{method,headers:body?{"Content-Type":"application/json","Idempotency-Key":pendingRequests.get(fingerprint)!}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error??"저장하지 못했습니다.");pendingRequests.delete(fingerprint);return result;}
export function UserManagement({advertiserId}:{advertiserId?:string}){
 const [users,setUsers]=useState<User[]>([]),[workspaces,setWorkspaces]=useState<Workspace[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("");
 const [selected,setSelected]=useState<User|null>(null),[review,setReview]=useState<User|null>(null),[workspace,setWorkspace]=useState(""),[name,setName]=useState(""),[role,setRole]=useState("ADVERTISER"),[status,setStatus]=useState("ACTIVE"),[ids,setIds]=useState<string[]>([]);
 const [approveRole,setApproveRole]=useState("ADVERTISER"),[reviewIds,setReviewIds]=useState<string[]>([]);
 const filterQuery=filter.startsWith("role:")?"&role="+filter.slice(5):filter?"&status="+filter:"";
 const modal=useRef<HTMLDialogElement>(null);
 const load=async()=>{const [u,w]=await Promise.all([api("/api/admin/users?limit=100"+filterQuery),api("/api/admin/advertisers?limit=100")]);setUsers(u);setWorkspaces(w)};
 useEffect(()=>{let live=true;Promise.all([api("/api/admin/users?limit=100"+filterQuery),api("/api/admin/advertisers?limit=100")]).then(([u,w])=>{if(live){setUsers(u);setWorkspaces(w)}}).catch(e=>{if(live)setNotice(e.message)});return()=>{live=false}},[filter]);
 useEffect(()=>{if(review)modal.current?.showModal();else modal.current?.close()},[review]);
 const edit=(u:User)=>{setSelected(u);setName(u.name??"");setRole(u.role);setStatus(u.status);setIds(u.members.map(m=>m.advertiserId));};
 const decide=async(user:User,action:string)=>{if(busy)return;setBusy(true);try{await flushServerStorage();await api("/api/admin/users","PATCH",{id:user.id,action,...(action==="approve"?{role:approveRole,advertiserIds:approveRole==="MANAGER"?reviewIds:[workspace]}:{})});setNotice(action==="approve"?"승인 및 광고주 연결이 완료되었습니다.":action==="reject"?"가입 요청을 거절했습니다.":"사용자를 비활성화했습니다.");setReview(null);setSelected(null);await load()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}};
 return <section className="admin-management"><h2>사용자 관리</h2><p>가입 대기 사용자를 승인하고 광고주를 연결해주세요. 권한 변경과 비활성화 시 기존 세션이 종료됩니다.</p>
 <div className="mvp-controls" aria-label="사용자 상태 필터">{[["","전체"],["PENDING","승인 대기"],["role:MANAGER","내부 마케터"],["role:ADVERTISER","광고주"],["ACTIVE","활성"],["DISABLED","비활성"]].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div>
 <div className="mvp-scroll"><table><thead><tr>{["이름 / 이메일","역할","담당 광고주","상태","가입일","관리"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{users.filter(u=>!advertiserId||["PENDING","INVITED"].includes(u.status)||u.members.some(m=>m.advertiserId===advertiserId)).map(u=><tr key={u.id}><td>{u.name}<small>{u.email}</small></td><td>{u.role}</td><td>{u.role==="MANAGER"&&<strong>{u.members.length}개 광고주<br/></strong>}{u.members.map(m=>workspaces.find(w=>w.id===m.advertiserId)?.name??m.advertiserId).join(", ")||"미할당"}</td><td>{["PENDING","INVITED"].includes(u.status)?<strong style={{color:"#6342bd",background:"#eee9ff",padding:"5px 8px",borderRadius:6}}>승인 대기</strong>:u.status}</td><td>{new Date(u.createdAt).toLocaleDateString("ko-KR")}</td><td>{["PENDING","INVITED"].includes(u.status)?<><button disabled={busy} onClick={()=>{setWorkspace(advertiserId??"");setApproveRole("ADVERTISER");setReviewIds(advertiserId?[advertiserId]:[]);setNotice("");setReview(u)}}>승인 및 광고주 연결</button><button disabled={busy} onClick={()=>decide(u,"reject")}>거절</button></>:<button onClick={()=>edit(u)}>연결·권한 수정</button>}{u.status!=="DISABLED"&&<button disabled={busy} onClick={()=>decide(u,"disable")}>비활성화</button>}</td></tr>)}</tbody></table></div>
 {users.length>=100&&<button onClick={async()=>{try{const more=await api("/api/admin/users?limit=100&after="+users.at(-1)!.id+filterQuery);setUsers([...users,...more]);if(!more.length)setNotice("모든 사용자를 불러왔습니다.")}catch(e){setNotice((e as Error).message)}}}>더 보기</button>}
 {selected&&<form className="admin-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await flushServerStorage();await api("/api/admin/users","PATCH",{id:selected.id,name,role,status,advertiserIds:ids});setNotice("사용자 정보가 저장되었습니다. 기존 세션이 종료되었습니다.");setSelected(null);await load()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}><h3>사용자 수정</h3><label>이름<input required value={name} onChange={e=>setName(e.target.value)}/></label><p>{selected.email}</p><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option>ADVERTISER</option><option>MANAGER</option><option>SUPER_ADMIN</option></select></label><label>사용자 상태<select value={status} onChange={e=>setStatus(e.target.value)}>{selected.status==="INVITED"?<option>INVITED</option>:<option>ACTIVE</option>}<option>DISABLED</option></select></label><fieldset><legend>{role==="MANAGER"?"담당 광고주 배정":"광고주 연결"}</legend><div>{ids.map(id=><button type="button" key={id} onClick={()=>setIds(ids.filter(value=>value!==id))} aria-label={(workspaces.find(w=>w.id===id)?.name??id)+" 배정 제거"}>{workspaces.find(w=>w.id===id)?.name??id} ×</button>)}</div>{workspaces.filter(w=>w.status==="ACTIVE").map(w=><label key={w.id}><input type="checkbox" checked={ids.includes(w.id)} onChange={e=>setIds(e.target.checked?[...ids,w.id]:ids.filter(id=>id!==w.id))}/>{w.name}</label>)}</fieldset><button className="mvp-primary" disabled={busy}>사용자 변경 저장</button><button type="button" onClick={()=>setSelected(null)}>취소</button></form>}
 <dialog ref={modal} onCancel={()=>setReview(null)} aria-labelledby="approval-title" style={{maxWidth:480,width:"calc(100% - 32px)",border:"1px solid #dce1df",borderRadius:16,padding:24}}>{review&&<form className="admin-form" onSubmit={e=>{e.preventDefault();void decide(review,"approve")}}><h3 id="approval-title">승인 및 광고주 연결</h3><p>{review.name}<br/>{review.email}</p><label>승인 역할<select value={approveRole} onChange={e=>setApproveRole(e.target.value)}><option value="ADVERTISER">ADVERTISER · 광고주 담당자</option><option value="MANAGER">MANAGER · 내부 마케터</option></select></label>{approveRole==="MANAGER"?<fieldset><legend>담당 광고주 (복수 선택)</legend>{workspaces.filter(w=>w.status==="ACTIVE").map(w=><label key={w.id}><input type="checkbox" checked={reviewIds.includes(w.id)} onChange={e=>setReviewIds(e.target.checked?[...reviewIds,w.id]:reviewIds.filter(id=>id!==w.id))}/>{w.name}</label>)}</fieldset>:<label>연결할 광고주<select required value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">광고주 선택</option>{workspaces.filter(w=>w.status==="ACTIVE").map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>}<p>권한: {approveRole}</p><button className="mvp-primary" disabled={busy||(approveRole==="MANAGER"?!reviewIds.length:!workspace)}>승인 및 연결</button><button type="button" disabled={busy} onClick={()=>setReview(null)}>취소</button><p role="status">{notice}</p></form>}</dialog>
 {!review&&<p role="status">{notice}</p>}</section>;
}
export function AdvertiserManagement(){const [items,setItems]=useState<Workspace[]>([]),[selected,setSelected]=useState<Workspace|null>(null),[name,setName]=useState(""),[industry,setIndustry]=useState(""),[productName,setProductName]=useState(""),[status,setStatus]=useState("ACTIVE"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{api("/api/admin/advertisers").then(setItems).catch(e=>setNotice(e.message))},[]);const edit=(w:Workspace|null)=>{setSelected(w);setName(w?.name??"");setIndustry(w?.industry??"");setProductName(w?.productName??"");setStatus(w?.status??"ACTIVE")};return <section className="admin-management"><h2>Workspace 관리</h2><div className="mvp-controls"><button onClick={()=>edit(null)}>새 광고주</button>{items.map(w=><span key={w.id}><button onClick={()=>edit(w)}>{w.name} 수정</button> <Link href={`/advertisers/${w.id}`}>사용자 보기</Link></span>)}</div><form className="admin-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await flushServerStorage();const saved=await api("/api/admin/advertisers",selected?"PATCH":"POST",{id:selected?.id,name,industry,productName,status});if(!selected){window.location.assign(`/connections?advertiser=${saved.id}`);}else{window.location.reload();}}catch(e){setNotice((e as Error).message);setBusy(false)}}}><label>광고주 이름<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>업종<input value={industry} onChange={e=>setIndustry(e.target.value)}/></label><label>대표 상품<input value={productName} onChange={e=>setProductName(e.target.value)}/></label><label>Workspace 상태<select value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>DISABLED</option></select></label><button disabled={busy}>{selected?"광고주 변경 저장":"광고주 생성"}</button></form><p role="status">{notice}</p></section>}
export function AuditViewer(){const [items,setItems]=useState<{id:string;createdAt:string;actorUserId:string;advertiserId:string|null;action:string;resource:string}[]>([]),[error,setError]=useState("");return <section><div className="mvp-heading"><h2>관리자 Audit Log</h2><button onClick={()=>api("/api/admin/audit").then(setItems).catch(e=>setError(e.message))}>최근 기록 조회</button></div><p>Operations History와 별도로 저장되는 서버 변경 기록입니다. 최근 100건을 표시합니다.</p><div className="mvp-scroll"><table><tbody>{items.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString("ko-KR")}</td><td>{a.actorUserId}</td><td>{a.action}</td><td>{a.resource}</td><td>{a.advertiserId??"—"}</td></tr>)}</tbody></table></div><p role="status">{error}</p></section>}
