"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {flushServerStorage} from "@/lib/server-storage";
type Workspace={id:string;name:string;industry:string;productName:string;status:string};
type User={id:string;name:string|null;email:string;role:string;status:string;lastLoginAt:string|null;members:{advertiserId:string}[]};
const pendingRequests=new Map<string,string>();
async function api(path:string,method="GET",body?:unknown){const fingerprint=JSON.stringify([path,method,body]);if(body&&!pendingRequests.has(fingerprint)){if(pendingRequests.size>=100)pendingRequests.delete(pendingRequests.keys().next().value!);pendingRequests.set(fingerprint,crypto.randomUUID())}const response=await fetch(path,{method,headers:body?{"Content-Type":"application/json","Idempotency-Key":pendingRequests.get(fingerprint)!}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error??"저장하지 못했습니다.");pendingRequests.delete(fingerprint);return result;}
export function UserManagement({advertiserId}:{advertiserId?:string}){
 const [users,setUsers]=useState<User[]>([]),[workspaces,setWorkspaces]=useState<Workspace[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState<User|null>(null),[name,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState("ADVERTISER"),[status,setStatus]=useState("INVITED"),[ids,setIds]=useState<string[]>(advertiserId?[advertiserId]:[]);
 const load=async()=>{const [u,w]=await Promise.all([api("/api/admin/users"),api("/api/admin/advertisers")]);setUsers(u);setWorkspaces(w)};
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[]);
 const edit=(u:User|null)=>{setSelected(u);setName(u?.name??"");setEmail(u?.email??"");setRole(u?.role??"ADVERTISER");setStatus(u?.status??"INVITED");setIds(u?.members.map(m=>m.advertiserId)??(advertiserId?[advertiserId]:[]));};
 return <section className="admin-management"><div className="mvp-heading"><h2>사용자 관리</h2><button onClick={()=>edit(null)}>사용자 초대 준비</button></div><p>초대는 7일간 유효합니다. 초대 사용자가 로그인 화면에서 이메일 인증을 마치면 활성화됩니다. 권한 변경 시 재로그인이 필요합니다.</p><div className="mvp-scroll"><table><thead><tr>{["이름 / 이메일","Role","광고주","상태","최근 로그인","관리"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{users.filter(u=>!advertiserId||u.members.some(m=>m.advertiserId===advertiserId)).map(u=><tr key={u.id}><td>{u.name}<small>{u.email}</small></td><td>{u.role}</td><td>{u.members.map(m=>workspaces.find(w=>w.id===m.advertiserId)?.name??m.advertiserId).join(", ")||"미할당"}</td><td>{u.status}</td><td>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString("ko-KR"):"—"}</td><td><button onClick={()=>edit(u)}>연결·권한 수정</button></td></tr>)}</tbody></table></div><form className="admin-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await flushServerStorage();await api("/api/admin/users",selected?"PATCH":"POST",{id:selected?.id,name,email,role,status,advertiserIds:ids});setNotice(selected?"사용자 정보가 저장되었습니다. 해당 사용자의 기존 세션이 종료되었습니다.":"초대가 준비되었습니다. 등록한 이메일로 로그인하도록 안내해 주세요.");edit(null);await load()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}><h3>{selected?"사용자 수정":"새 사용자 초대"}</h3><label>이름<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>이메일<input type="email" required disabled={!!selected} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option>ADVERTISER</option><option>ADMIN</option></select></label>{selected&&<label>사용자 상태<select value={status} onChange={e=>setStatus(e.target.value)}>{selected.status==="INVITED"?<option>INVITED</option>:<option>ACTIVE</option>}<option>DISABLED</option></select></label>}<fieldset><legend>광고주 연결</legend>{workspaces.filter(w=>w.status==="ACTIVE").map(w=><label key={w.id}><input type="checkbox" checked={ids.includes(w.id)} onChange={e=>setIds(e.target.checked?[...ids,w.id]:ids.filter(id=>id!==w.id))}/>{w.name}</label>)}</fieldset><button className="mvp-primary" disabled={busy}>{busy?"저장 중…":selected?"사용자 변경 저장":"초대 등록"}</button></form><p role="status">{notice}</p></section>;
}
export function AdvertiserManagement(){const [items,setItems]=useState<Workspace[]>([]),[selected,setSelected]=useState<Workspace|null>(null),[name,setName]=useState(""),[industry,setIndustry]=useState(""),[productName,setProductName]=useState(""),[status,setStatus]=useState("ACTIVE"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{api("/api/admin/advertisers").then(setItems).catch(e=>setNotice(e.message))},[]);const edit=(w:Workspace|null)=>{setSelected(w);setName(w?.name??"");setIndustry(w?.industry??"");setProductName(w?.productName??"");setStatus(w?.status??"ACTIVE")};return <section className="admin-management"><h2>Workspace 관리</h2><div className="mvp-controls"><button onClick={()=>edit(null)}>새 광고주</button>{items.map(w=><span key={w.id}><button onClick={()=>edit(w)}>{w.name} 수정</button> <Link href={`/advertisers/${w.id}`}>사용자 보기</Link></span>)}</div><form className="admin-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await flushServerStorage();await api("/api/admin/advertisers",selected?"PATCH":"POST",{id:selected?.id,name,industry,productName,status});window.location.reload()}catch(e){setNotice((e as Error).message);setBusy(false)}}}><label>광고주 이름<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>업종<input value={industry} onChange={e=>setIndustry(e.target.value)}/></label><label>대표 상품<input value={productName} onChange={e=>setProductName(e.target.value)}/></label><label>Workspace 상태<select value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>DISABLED</option></select></label><button disabled={busy}>{selected?"광고주 변경 저장":"광고주 생성"}</button></form><p role="status">{notice}</p></section>}
export function AuditViewer(){const [items,setItems]=useState<{id:string;createdAt:string;actorUserId:string;action:string;resource:string}[]>([]),[error,setError]=useState("");return <section><div className="mvp-heading"><h2>관리자 Audit Log</h2><button onClick={()=>api("/api/admin/audit").then(setItems).catch(e=>setError(e.message))}>최근 기록 조회</button></div><p>Operations History와 별도로 저장되는 서버 변경 기록입니다. 최근 100건을 표시합니다.</p><div className="mvp-scroll"><table><tbody>{items.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString("ko-KR")}</td><td>{a.actorUserId}</td><td>{a.action}</td><td>{a.resource}</td></tr>)}</tbody></table></div><p role="status">{error}</p></section>}
