const {createServer}=require('node:http');
const {spawnSync,spawn}=require('node:child_process');
const {randomBytes}=require('node:crypto');
const {resolve}=require('node:path');
const env={...process.env,APP_ENV:"development",RATE_LIMIT_STORE:"memory",DATABASE_URL:'file:./browser-test.db',AUTH_SECRET:randomBytes(48).toString('hex'),AUTH_URL:'http://localhost:3100',AUTH_RESEND_KEY:'local-transport-only',AUTH_EMAIL_FROM:'login@intentbridge.test',RUST_LOG:'info',GA4_DATA_MODE:'mock',GA4_PROPERTY_ID:'',GA4_PROPERTY_MAP:'',GOOGLE_APPLICATION_CREDENTIALS:''};
for(const args of [['node_modules/prisma/build/index.js','migrate','deploy'],['node_modules/tsx/dist/cli.mjs','scripts/seed.ts']]){const result=spawnSync(process.execPath,args,{env,stdio:'inherit'});if(result.status)process.exit(result.status)}
const mail=new Map();let rejectMail=false;
const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;res.setHeader('content-type','application/json');const url=new URL(req.url,'http://127.0.0.1');if(req.method==='POST'&&url.pathname==='/control'){rejectMail=JSON.parse(body).rejectMail===true;res.end('{}')}else if(req.method==='POST'&&url.pathname==='/mail'){if(rejectMail){res.statusCode=503;res.end('{}');return;}const item=JSON.parse(body);mail.set(String(item.to),item);res.end('{}')}else if(req.method==='GET'&&url.pathname==='/mail'){res.end(JSON.stringify(mail.get(url.searchParams.get('email'))??null))}else{res.statusCode=404;res.end('{}')}});
server.listen(3101,'127.0.0.1',()=>{const child=spawn(process.execPath,['--require',resolve('scripts/test-mail-preload.cjs'),'node_modules/next/dist/bin/next','start','--port','3100'],{env,stdio:'inherit'});child.on('exit',code=>{server.close();process.exit(code??0)});process.on('SIGTERM',()=>child.kill());process.on('SIGINT',()=>child.kill())});
