"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useDashboard} from '@/components/app-shell';
import {useUserRole} from '@/context/user-role-context';
import {can} from '@/lib/permissions';
import {connectorCatalog,connections,stateNames,workspaceHealth} from './catalog';
import {usePlatform} from './use-platform';
import {WorkspacePlatform} from './workspace-platform';
import type {ConnectorDefinition} from '@/types/platform';
import './platform.css';
export function ConnectionWorkspace(){const d=useDashboard();return <ConnectionContent key={d.advertiser.id}/>;}
function ConnectionContent(){
 const d=useDashboard(),{user}=useUserRole(),model=usePlatform(d.advertiser.id),[selected,setSelected]=useState<ConnectorDefinition|null>(null),[wizard,setWizard]=useState(false),[filter,setFilter]=useState('all');
 const {view}=model,admin=can(user.role,'MANAGE_CONNECTIONS'),synced=Object.values(view?.document.connections??{}).filter(c=>c?.state==='healthy'),last=synced.map(c=>c!.lastSync!).sort().at(-1);
 return <div className="platform"><WorkspacePlatform/><section className="platform-panel"><header><div><span className="platform-tag">DEMO CONNECTION</span><h2>데이터 연결 센터</h2><p>실제 OAuth·광고 API 호출 없이 계정 선택부터 데이터 확인까지 경험하세요.</p></div><label>연결 상태<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option><option value="healthy">정상</option><option value="disconnected">연결 안 됨</option></select></label></header><div className="platform-source"><span>{view?workspaceHealth(view.document):'설정 확인 중'}</span><span>데이터 연결 {synced.length}/{connectorCatalog.length}</span><span>마지막 수집 {last?new Date(last).toLocaleString('ko-KR'):'수집 전'}</span><span>수집 오류 {Object.values(view?.document.connections??{}).filter(c=>c?.state==='error').length}건</span></div>
 {!admin&&<p>연결 설정은 최고 관리자가 관리합니다. 담당 광고주의 데이터 상태를 확인할 수 있습니다.</p>}
 <div className="platform-connectors">{connectorCatalog.filter(c=>filter==='all'||(view?.document.connections[c.id]?.state??'disconnected')===filter).map(c=>{const current=view?.document.connections[c.id];return <article key={c.id}><span className="platform-icon">{c.icon}</span><h3><button onClick={()=>{setSelected(c);setWizard(false);}}>{c.name}</button></h3><p>{c.description}</p><span className="platform-tag">{stateNames[current?.state??'disconnected']} · 데모 연결</span><p>최근 동기화: {current?.lastSync?new Date(current.lastSync).toLocaleString('ko-KR'):'아직 없음'}</p><small>수집 데이터: {(current?.fields??c.fields).join(' · ')}</small><div className="platform-actions"><button onClick={()=>{setSelected(c);setWizard(false);}}>데이터 확인</button>{admin&&<button disabled={!view||model.busy} onClick={()=>{setSelected(c);setWizard(true);}}>{current?'연결 설정':'연결하기'}</button>}{admin&&current&&<button disabled={model.busy} onClick={()=>model.save({action:'refresh',connector:c.id})}>새로고침</button>}</div></article>;})}</div><p role="alert">{model.error}</p></section>
 <section className="platform-panel" id="platform-data"><header><div><span className="platform-tag">DEMO DATA</span><h2>데이터 현황 · 최근 {d.period}일</h2><p>GA4의 구매는 직접 구매 + 재방문 구매입니다. 다른 매체 수치를 중복 합산하지 않습니다.</p></div>{admin&&<button disabled={model.busy||view?.document.connections.ga4?.state!=='healthy'} onClick={()=>model.save({action:'validate'})}>{view?.document.validated?'데이터 확인 완료':'데이터 확인 완료로 표시'}</button>}</header><div className="platform-data-grid">{connectorCatalog.map(c=><div key={c.id}><h3>{c.name}</h3>{connections.get(c.id).collect(d).map(m=><p key={m.label}><span>{m.label}</span><b>{m.value.toLocaleString('ko-KR')}{m.unit??''}</b></p>)}{!['ga4','meta','ai'].includes(c.id)&&<small>연결 UX 데모 · 현재 기준 데이터에 매체 실적이 없습니다.</small>}</div>)}</div><details><summary>Advanced · Demo Mapping</summary><dl><dt>GA4 구매 ↔ 광고 전환</dt><dd>purchase ↔ conversion (매체별 기여 기간이 달라 중복 합산 금지)</dd><dt>Revenue</dt><dd>purchaseRevenue</dd><dt>Cart</dt><dd>add_to_cart</dd></dl></details><Link href={`/dashboard?advertiser=${d.advertiser.id}`}>대시보드 →</Link></section>
 {selected&&<ConnectorDialog key={`${selected.id}:${wizard}`} definition={selected} wizard={wizard} model={model} close={()=>setSelected(null)} admin={admin}/>}
 </div>;
}
function ConnectorDialog({definition:c,wizard,model,close,admin}:{definition:ConnectorDefinition;wizard:boolean;model:ReturnType<typeof usePlatform>;close:()=>void;admin:boolean}){
 const ref=useRef<HTMLDialogElement>(null),d=useDashboard(),[step,setStep]=useState(wizard?0:-1),[account,setAccount]=useState(c.accounts[0]),[property,setProperty]=useState(c.properties[0]),[fields,setFields]=useState(c.fields),[message,setMessage]=useState(''),[testing,setTesting]=useState(false);
 useEffect(()=>{const previous=document.activeElement;ref.current?.showModal();return()=>{if(previous instanceof HTMLElement)previous.focus();};},[]);
 const titles=['연결 방식','계정 선택','Property / 광고계정 선택','수집 데이터 선택','연결 테스트','연결 완료'];
 return <dialog className="platform-dialog" ref={ref} onCancel={close} aria-labelledby="connection-title"><button className="platform-close" onClick={close}>닫기</button><span className="platform-tag">DEMO CONNECTION</span><h2 id="connection-title">{c.name}</h2>{step<0?<><p>{c.description}</p><p>상태: {stateNames[model.view?.document.connections[c.id]?.state??'disconnected']}</p><p>수집 항목: {c.fields.join(' · ')}</p><p>최근 동기화: {model.view?.document.connections[c.id]?.lastSync??'수집 전'}</p>{connections.get(c.id).collect(d).map(m=><p key={m.label}>{m.label}: {m.value.toLocaleString('ko-KR')}{m.unit}</p>)}{admin&&<button onClick={()=>setStep(0)}>연결 설정</button>}</>:<><p>STEP {step+1} / 6 · {titles[step]}</p><progress value={step+1} max={6}/>{step===0&&<p>DEMO MODE · {c.id==='ga4'?'Google 계정':'광고 계정'} 연결 과정을 데모로 진행합니다. 실제 로그인·OAuth·API 요청은 없습니다.</p>}{step===1&&<label>계정 선택<select value={account} onChange={e=>setAccount(e.target.value)}>{c.accounts.map(a=><option key={a}>{a}</option>)}</select></label>}{step===2&&<label>Property / 광고계정<select value={property} onChange={e=>setProperty(e.target.value)}>{c.properties.map(p=><option key={p}>{p}</option>)}</select></label>}{step===3&&<fieldset><legend>수집 데이터</legend>{c.fields.map(f=><label key={f}><input type="checkbox" checked={fields.includes(f)} onChange={e=>setFields(e.target.checked?[...fields,f]:fields.filter(v=>v!==f))}/>{f}</label>)}</fieldset>}{step===4&&<><p>{account} · {property}</p><p>{fields.join(' · ')}</p><button disabled={testing||model.busy} onClick={async()=>{setTesting(true);const test=await connections.get(c.id).test({account,property,fields});setMessage(test.message);if(test.ok&&await model.save({action:'connect',connector:c.id,account,property,fields}))setStep(5);setTesting(false);}}>{testing?'연결 중…':'데모 연결 테스트'}</button></>}{step===5&&<><h3>정상 · 데모 연결 완료</h3><p>선택한 수집 항목을 저장했습니다. 실제 광고 계정은 변경하지 않았습니다.</p><a href={`/connections?advertiser=${d.advertiser.id}#platform-data`} onClick={e=>{e.preventDefault();const target=new URL(e.currentTarget.href);if(location.pathname===target.pathname&&location.search===target.search){location.hash=target.hash;location.reload();}else location.assign(target.href);}}>데이터 확인하기 →</a></>}<p role="status">{message}</p><p role="alert">{model.error}</p><div className="platform-actions">{step>0&&step<5&&<button disabled={testing||model.busy} onClick={()=>setStep(step-1)}>이전</button>}{step<4&&<button disabled={step===3&&!fields.length} onClick={()=>setStep(step+1)}>다음</button>}</div></>}</dialog>;
}
