"use client";
import Link from 'next/link';
import {Bell,Search} from 'lucide-react';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {useUserRole} from '@/context/user-role-context';
import {can} from '@/lib/permissions';
import {canAccessRoute} from '@/lib/route-permissions';
import {loadAssignedSummary,loadAdminSummary,type WorkspaceSummary} from '@/lib/workspace-summary';
import type {Advertiser,Period} from '@/types/domain';
import {usePlatform} from './use-platform';
import {readAppSettings,defaultAppSettings} from '@/lib/app-settings';
import './platform.css';
export function PlatformToolbar({advertisers,id,period,select}:{advertisers:Advertiser[];id:string;period:Period;select:(id:string,period:Period)=>void}){
 const {user}=useUserRole(),path=usePathname(),[query,setQuery]=useState(''),[quickQuery,setQuickQuery]=useState(''),[rows,setRows]=useState<WorkspaceSummary[]>([]),[error,setError]=useState(''),[recent,setRecent]=useState<string[]>([]),[read,setRead]=useState<string[]>([]);
 const operator=can(user.role,'MANAGE_CAMPAIGN'),platform=usePlatform(id),[branding,setBranding]=useState(defaultAppSettings);
 useEffect(()=>{const sync=()=>setBranding(readAppSettings());sync();window.addEventListener('intentbridge-settings',sync);return()=>window.removeEventListener('intentbridge-settings',sync);},[]);
 useEffect(()=>{setRows([]);setError('');if(!operator)return;let active=true;(user.role==='manager'?loadAssignedSummary:loadAdminSummary)(period).then(items=>{if(active)setRows(items);}).catch(()=>{if(active)setError('업무 알림을 불러오지 못했습니다.');});return()=>{active=false};},[operator,user.role,user.id,period,id]);
 useEffect(()=>{try{const previous=JSON.parse(sessionStorage.getItem(`intentbridge:recent:${user.id}`)||'[]');const next=[id,...(Array.isArray(previous)?previous.filter(v=>typeof v==='string'&&v!==id):[])].slice(0,5);setRecent(next);sessionStorage.setItem(`intentbridge:recent:${user.id}`,JSON.stringify(next));const saved=JSON.parse(sessionStorage.getItem(`intentbridge:read:${user.id}`)||'[]');setRead(Array.isArray(saved)?saved.filter(v=>typeof v==='string'):[]);}catch{/* Browser preferences are optional. */}},[id,user.id]);
 const alerts=[...(platform.view?.document.activity.slice(0,3)??[]).map(a=>({id:a.id,name:advertisers.find(v=>v.id===id)?.name??'',message:a.label,href:`/connections?advertiser=${id}`})),...rows.map(r=>({id:`${r.dashboard.advertiser.id}:${period}:${r.reason}:${r.pending}`,name:r.dashboard.advertiser.name,message:r.reason,href:`/${r.attention?'operations':'funnel'}?advertiser=${r.dashboard.advertiser.id}&period=${period}`}))];
 const mark=(id:string)=>{const next=read.includes(id)?read.filter(v=>v!==id):[...read,id].slice(-200);setRead(next);try{sessionStorage.setItem(`intentbridge:read:${user.id}`,JSON.stringify(next));}catch{/* Read flags are browser-session preferences only. */}};
 return <><div className="platform-toolbar">{user.role==='super_admin'&&<span title="현재 계정의 회사 표시 설정">{branding.logoText??'IB'} · {branding.companyName??'IntentBridge'}</span>}{operator&&<><div className="platform-search"><label><Search size={14}/> 광고주 · 캠페인 검색<input type="search" aria-label="광고주 · 캠페인 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="광고주 또는 캠페인 이름"/></label>{query&&<div className="platform-search-results" role="status">{advertisers.filter(a=>a.name.toLowerCase().includes(query.toLowerCase())).map(a=><Link key={a.id} href={`/?advertiser=${a.id}&period=${period}`} onClick={()=>setQuery('')}>{a.name}</Link>)}{rows.flatMap(r=>r.campaigns.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(c=><Link key={`${r.dashboard.advertiser.id}:${c.id}`} href={`/campaigns?advertiser=${r.dashboard.advertiser.id}&period=${period}`}>{r.dashboard.advertiser.name} · {c.name}</Link>))}</div>}</div><details><summary><Bell size={18}/> 알림 {alerts.filter(a=>!read.includes(a.id)).length}</summary><div className="platform-popover"><b>오늘 확인할 내용 · DEMO</b>{error&&<p role="alert">{error}</p>}{!alerts.length&&!error&&<p>확인할 알림이 없습니다.</p>}{alerts.map(a=><article key={a.id}><Link href={a.href}>{a.name}<br/>{a.message}</Link><button onClick={()=>mark(a.id)}>{read.includes(a.id)?'안 읽음으로 표시':'읽음으로 표시'}</button></article>)}<small>읽음 상태는 현재 브라우저 세션에 저장됩니다.</small></div></details></>}
 {advertisers.length>1&&<details><summary>광고주 빠른 전환</summary><div className="platform-popover"><label>광고주 검색<input aria-label="빠른 전환 광고주 검색" value={quickQuery} onChange={e=>setQuickQuery(e.target.value)}/></label><b>최근 광고주</b>{recent.map(key=>advertisers.find(a=>a.id===key)).filter((a):a is Advertiser=>!!a).map(a=><button key={a.id} onClick={e=>{e.currentTarget.closest("details")?.removeAttribute("open");setQuickQuery('');select(a.id,period);}}>{a.name}</button>)}<p>접근 가능한 광고주 전체</p>{advertisers.filter(a=>a.name.includes(quickQuery)).map(a=><button key={a.id} onClick={e=>{e.currentTarget.closest("details")?.removeAttribute("open");setQuickQuery('');select(a.id,period);}}>{a.name}</button>)}</div></details>}</div>
 <div className="platform-flow" aria-label="광고 운영 흐름">{[['/advertisers','광고주 · 담당자'],['/connections','연결 · 데이터 확인'],['/','대시보드'],['/funnel','고객 여정'],['/performance','성과 개선'],['/campaigns','캠페인'],['/operations','광고 운영'],['/reports','성과 보고서']].filter(([href])=>canAccessRoute(user,href)).map(([href,label])=><Link key={href} href={`${href}?advertiser=${id}&period=${period}`} aria-current={path===href?'page':undefined}>{label} →</Link>)}</div></>;
}
