"use client";
import {useEffect,useState} from 'react';
import {useDashboard} from '@/components/app-shell';
import {useUserRole} from '@/context/user-role-context';
import {loadWorkspaceSummary} from '@/lib/workspace-summary';
import {mockTrendEndDate} from '@/lib/performance-trend';
import {downloadText} from '@/lib/download';
import type {DailyMetric} from '@/types/mvp';
import './platform.css';
export type ReportRange='7'|'30'|'month'|'previous';
export function reportRows(rows:DailyMetric[],range:ReportRange){const end=new Date(`${mockTrendEndDate}T00:00:00Z`),month=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),1)),previous=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-1,1));return rows.filter(r=>range==='7'?r.date>=new Date(end.getTime()-6*86400000).toISOString().slice(0,10):range==='30'?true:range==='month'?r.date>=month.toISOString().slice(0,10):r.date>=previous.toISOString().slice(0,10)&&r.date<month.toISOString().slice(0,10));}
export function ReportPeriod(){const d=useDashboard(),{user}=useUserRole(),[rows,setRows]=useState<DailyMetric[]>([]),[range,setRange]=useState<ReportRange>('30'),[error,setError]=useState('');useEffect(()=>{let active=true;setRows([]);setError('');loadWorkspaceSummary({advertiserId:d.advertiser.id,period:30}).then(s=>{if(active)setRows(s.trend);}).catch(()=>{if(active)setError('일별 보고서를 불러오지 못했습니다.');});return()=>{active=false};},[d.advertiser.id]);const selected=reportRows(rows,range),totals=selected.reduce((sum,r)=>({spend:sum.spend+r.spend,purchases:sum.purchases+r.purchases,revenue:sum.revenue+r.revenue,traffic:sum.traffic+r.traffic}),{spend:0,purchases:0,revenue:0,traffic:0});
 const exportData=(format:'html'|'csv'|'json')=>{const title=`${d.advertiser.name} · ${selected.at(0)?.date??''} ~ ${selected.at(-1)?.date??''}`,escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const csv=['Date,Spend,Users,Purchase,Revenue',...selected.map(r=>[r.date,r.spend,r.traffic,r.purchases,r.revenue].join(','))].join('\n');const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>IntentBridge 보고서</title><body style="font-family:sans-serif;max-width:900px;margin:32px auto;padding:20px"><h1>${escape(title)}</h1><p>DEMO DATA · 제공된 일자만 집계 · 전체 월 실적이 아닐 수 있습니다.</p><h2>성과 요약</h2><p>유입 ${totals.traffic} · 구매 ${totals.purchases} · 매출 ${totals.revenue.toLocaleString()}원 · 광고비 ${totals.spend.toLocaleString()}원</p><h2>개선 · 운영</h2><p>고객 여정의 이탈 구간과 운영 화면의 검토 대기 제안을 확인하세요. 실제 광고 집행은 없습니다.</p><table><tr><th>날짜</th><th>광고비</th><th>유입</th><th>구매</th><th>매출</th></tr>${selected.map(r=>`<tr><td>${r.date}</td><td>${r.spend}</td><td>${r.traffic}</td><td>${r.purchases}</td><td>${r.revenue}</td></tr>`).join('')}</table></body></html>`;downloadText(`IntentBridge_Report_${d.advertiser.id}_${range}.${format}`,format==='html'?html:format==='csv'?csv:JSON.stringify({label:'DEMO DATA',title,totals,rows:selected},null,2),format==='html'?'text/html;charset=utf-8':format==='csv'?'text/csv;charset=utf-8':'application/json');};
 return <section className="platform-panel"><header><div><span className="platform-tag">DEMO DATA</span><h2>보고서 다운로드</h2></div><div className="platform-calendar"><label>보고서 기간<select value={range} onChange={e=>setRange(e.target.value as ReportRange)}><option value="month">이번 달</option><option value="previous">지난달</option><option value="7">최근 7일</option><option value="30">최근 30일</option></select></label><button disabled={!selected.length} onClick={()=>exportData('html')}>보고서 다운로드 · HTML</button></div></header><p>데모 기준일 {mockTrendEndDate} · {selected.at(0)?.date??'—'} ~ {selected.at(-1)?.date??'—'} · {selected.length}일 제공. 월 전체가 없으면 제공된 날짜만 집계합니다.</p><div className="platform-source">{Object.entries(totals).map(([key,value])=><span key={key}>{({spend:'광고비',purchases:'구매',revenue:'매출',traffic:'유입'})[key]} <b>{value.toLocaleString('ko-KR')}</b></span>)}</div><p>아래 워크스페이스 상세 분석은 상단의 {d.period}일 기준입니다. 이 다운로드는 30일 일별 데이터 중 선택 범위만 포함합니다.</p>{user.role!=='advertiser'&&<details><summary>Advanced · 데이터 내보내기</summary><button disabled={!selected.length} onClick={()=>exportData('csv')}>CSV</button><button disabled={!selected.length} onClick={()=>exportData('json')}>JSON</button></details>}<p role="alert">{error}</p></section>;
}
