"use client";
import Link from "next/link";
import {useState} from "react";
import {useSummary} from "./use-summary";
import {useGA4} from "@/features/ga4/provider";
import {simulate} from "@/lib/simulation";
import {getGA4Baseline,simulateGA4Baseline} from "@/lib/ga4/simulation";
import {scenarios} from "@/data/mock/simulation-config";
import {number,won,percent} from "@/lib/format";
export function AdvertiserDashboard({view="dashboard"}:{view?:"dashboard"|"funnel"|"performance"|"campaigns"|"reports"}){const {data,error}=useSummary(),ga4=useGA4(),[scenario,setScenario]=useState("recommended");if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">성과를 불러오는 중…</p>;const s=ga4.mode==="real"?ga4.data?.snapshot:undefined,o=s?.overview,base=data.baseline,choice=scenarios.find(s=>s.id===scenario)??scenarios[1],forecast=simulate(base,choice.levers),realForecast=s?simulateGA4Baseline(getGA4Baseline(s),choice.levers.checkout):null,purchases=o?.purchases??data.dashboard.totals.purchases,revenue=o?.purchaseRevenue??data.dashboard.totals.revenue,predicted=realForecast?.purchases??forecast.totalPurchases,predictedRevenue=realForecast?.purchaseRevenue??forecast.revenue,money=(v:number)=>o?new Intl.NumberFormat("ko-KR",{style:"currency",currency:o.currency}).format(v):won(v),insight=s?"고객 행동별 이용자 수를 확인해 보세요. 실제 순차 이탈은 아직 측정하지 않습니다.":data.insight;
const kpis=<section><h2>이번 기간 성과</h2><div className="ux-kpis">{[["구매",`${number(purchases)}건`],["매출",money(revenue)],["광고비",o?"미연결":won(data.dashboard.totals.spend)],["ROAS",o?"미연결":percent(data.dashboard.totals.roas)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>;
const opportunity=<section className="ux-opportunity"><span className="ux-tag">DEMO FORECAST · 예상 성과</span><h2>성과 개선 기회</h2><p>{choice.name==="공격적"?"적극적":choice.name} 개선안 기준 · {s?"구매율 변화 가정, 평균 구매 매출 고정":"기존 성과 예측 엔진의 개선 가정"}</p><div className="ux-kpis"><div><span>예상 구매 변화</span><strong>{predicted-purchases>=0?"+":""}{number(predicted-purchases)}건</strong></div><div><span>예상 매출 변화</span><strong>{money(predictedRevenue-revenue)}</strong></div></div>{view!=="performance"&&<Link className="ux-action" href="/performance">개선안 자세히 보기 →</Link>}</section>;
const status=<section><h2>현재 광고 상태 <small>MOCK AD DATA</small></h2><div className="ux-inline"><span>운영 중 <b>{data.active}</b></span><span>확인 필요 <b>{data.attention}</b></span><span>최근 {data.dashboard.period}일 변경 <b>{data.recent}</b></span></div><p>{data.active?`관리자가 확인 중인 운영 항목 ${data.pending}개` : "아직 운영 중인 광고가 없습니다."}</p></section>;
const rows=s?s.daily.map(d=>({date:d.date,purchases:d.purchases})):data.trend,max=Math.max(1,...rows.map(r=>r.purchases));
const trend=<section><h2>최근 구매 추이</h2><p>{s?"REAL GA4 DATA · 날짜별 구매":"MOCK DATA · 기간 집계를 배분한 예시 추이"}</p>{rows.length?<><svg className="ux-trend" viewBox="0 0 600 130" role="img" aria-label="최근 일별 구매 추이"><title>최근 일별 구매 추이</title><line x1="8" x2="592" y1="118" y2="118" stroke="#ccd6d1"/><polyline points={rows.map((r,i)=>`${8+i*584/Math.max(1,rows.length-1)},${118-r.purchases/max*106}`).join(" ")} fill="none" stroke="#258a73" strokeWidth="3"/></svg><div className="ux-inline"><span>{rows[0].date}</span><span>최대 {max}건</span><span>{rows.at(-1)?.date}</span></div><details><summary>일별 수치 보기</summary><div className="ux-table"><table><thead><tr><th>날짜</th><th>구매</th></tr></thead><tbody>{rows.map(r=><tr key={r.date}><td>{r.date}</td><td>{r.purchases}건</td></tr>)}</tbody></table></div></details></>:<p>조회 기간에 기록된 구매 추이가 없습니다.</p>}</section>;
return <div className="ux-workspace" data-testid={`advertiser-${view}`}><p className="ux-subtitle">{s?"GA4 실측 성과 · 광고 운영은 Mock":"MOCK DATA · 예시 데이터"} · {data.dashboard.advertiser.name} · {data.dashboard.period}일</p>{view==="campaigns"?<section><h2>광고 현황</h2><p>관리자가 운영하는 광고를 조회합니다. 아래 수치는 MOCK AD DATA이며 예상 성과와 구분됩니다.</p>{data.campaigns.length?<div className="ux-table"><table><thead><tr>{["캠페인명","목표","일 예산","운영 상태","구매","ROAS"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.campaigns.map(c=><tr key={c.id}><th>{c.name}</th><td>{({Purchase:"구매", "Recover Cart":"장바구니 고객 재방문", "Recover Checkout":"결제 고객 재방문", "Revisit Product":"상품 재방문",Lead:"문의 확보",Custom:"맞춤 목표"})[c.objective]}</td><td>{won(c.budget)}</td><td>{({"MOCK ACTIVE":"운영 중 (Mock)",READY:"준비 완료",PAUSED:"일시 중지",DRAFT:"초안"})[c.status]}</td><td>{c.purchases}건</td><td>{c.roas===null?"산출 불가":percent(c.roas)}</td></tr>)}</tbody></table></div>:<p>아직 운영 중인 광고가 없습니다.</p>}{status}</section>:view==="funnel"?<><section><h2>고객이 구매까지 이동하는 과정</h2><p>{insight}</p><ol className="ux-journey">{s?[{label:"유입",users:s.overview.users},...s.events.map(e=>({label:({viewContent:"상품 확인",addToCart:"장바구니",beginCheckout:"결제",purchase:"구매"})[e.key],users:e.users}))].map((r,i)=><li key={r.label}><span>{i+1}. {r.label}</span><strong>{number(r.users)}명</strong><small>이벤트별 사용자 · 순차 전환율 미측정</small></li>):data.stages.map((r,i)=><li key={r.id}><span>{i+1}. {["유입","상품 확인","장바구니","결제","구매"][i]??r.label}</span><strong>{number(r.users)}명</strong><small>{r.conversionRate===null?"분석 시작":`이전 단계 대비 ${percent(r.conversionRate)} · 이탈 ${number(r.dropOff)}명`}</small></li>)}</ol></section><Link className="ux-action" href="/performance">개선 가능한 부분 살펴보기 →</Link></>:view==="performance"?<><section><h2>현재 성과</h2><strong className="ux-big">구매 {number(purchases)}건</strong><p>{insight}</p></section><section><h2>추천 개선안</h2><div className="ux-scenarios">{scenarios.map(c=><button key={c.id} aria-pressed={scenario===c.id} onClick={()=>setScenario(c.id)}>{c.id==="aggressive"?"적극적":c.name}</button>)}</div><p>{s?"구매 완료 비율의 개선 가능성을 비교합니다.":"구매 동선을 개선하고 재방문 광고의 효율을 높이는 가정입니다."}</p></section>{opportunity}<p>현재 {number(purchases)}건 → 개선 후 예상 {number(predicted)}건. 예상값이며 성과를 보장하지 않습니다.</p></>:<>{kpis}<section className="ux-insight"><span>현재 가장 중요한 내용</span><h2>{insight}</h2>{view==="reports"&&!s&&<p>재방문 광고를 통해 {data.dashboard.retargeting.recoveredPurchases}건의 추가 구매가 발생한 예시입니다.</p>}</section>{opportunity}{status}{trend}</>}</div>;
}
