"use client";
import Link from "next/link";
import {MockReportSummary} from "./mock-report-summary";
import {readAppSettings} from "@/lib/app-settings";
import {readCampaignStore} from "@/lib/campaign-store";
import {readOperations} from "@/lib/operations-store";
import {useState} from "react";
import {useGA4} from "./provider";
import {number} from "@/lib/format";
import {downloadText} from "@/lib/download";
import {escapeHtml} from "@/lib/export-service";
import {getGA4Baseline,simulateGA4Baseline} from "@/lib/ga4/simulation";
import {scenarios} from "@/data/mock/simulation-config";
export function GA4AnalyticsView({page}:{page:"overview"|"funnel"|"reports"|"performance"}){const {data,query}=useGA4(),[lift,setLift]=useState(0);const s=data?.snapshot;if(!s)return <p>GA4 데이터가 없습니다. Connections에서 설정을 확인하세요.</p>;const o=s.overview,money=(v:number)=>new Intl.NumberFormat("ko-KR",{style:"currency",currency:o.currency}).format(v),baseline=getGA4Baseline(s),forecast=simulateGA4Baseline(baseline,page==="reports"?(scenarios.find(x=>x.id===readAppSettings().forecastScenario)?.levers.checkout??0):lift);
 const exportReport=()=>{const e=escapeHtml;downloadText(`GA4_${s.advertiserId}_${s.period}D.html`,`<!doctype html><html lang="ko"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>IntentBridge GA4 Report</title><style>body{font:16px/1.8 Arial;padding:40px;max-width:960px;margin:auto}td,th{padding:12px;text-align:left;border-bottom:1px solid #ddd}table{width:100%}</style><h1>IntentBridge · Executive Report</h1><p>${e(s.advertiserId)} · ${s.period}일 · ${e(s.timezone)} · yesterday 종료</p><p>GA4 · REAL / Meta · MOCK / Forecast · DEMO</p><p>Users ${number(o.users)} · Sessions ${number(o.sessions)} · Purchase ${number(o.purchases)} · Purchase Revenue ${e(money(o.purchaseRevenue))}</p><h2>이벤트 사용자</h2><ul>${s.events.map(x=>`<li>${e(x.eventName)}: ${x.users}명 · ${x.found?"FOUND":"EVENT NOT DETECTED"}</li>`).join("")}</ul><p>이벤트별 사용자는 순차 코호트가 아닙니다. 실제 이탈·Audience·회수 구매를 추정하지 않습니다.</p>${s.warnings.map(w=>`<p>${e(w)}</p>`).join("")}<h2>DEMO FORECAST</h2><p>실측 Baseline 위 구매율 개선 가정: ${forecast.purchases}건 / ${e(money(forecast.purchaseRevenue))}. 평균 구매 매출 고정, 광고비/재공략 영향 미포함.</p><h2>Campaign / Operations · MOCK AD DATA</h2><ul>${readCampaignStore(query.advertiserId).campaigns.slice(0,3).map(c=>`<li>${e(c.name)} · ${e(c.status)}</li>`).join("")||"<li>Mock 캠페인 없음</li>"}</ul><ul>${readOperations(query.advertiserId).history.slice(0,3).map(h=>`<li>${e(h.campaignName)} · ${e(h.type)} · ${e(h.status)}</li>`).join("")}</ul><h2>Daily GA4 Data</h2><table><tr><th>Date</th><th>Users</th><th>Sessions</th><th>Purchase</th><th>Purchase Revenue</th></tr>${s.daily.map(d=>`<tr><td>${d.date}</td><td>${d.users}</td><td>${d.sessions}</td><td>${d.purchases}</td><td>${e(money(d.purchaseRevenue))}</td></tr>`).join("")}</table><p>광고비·CPA·ROAS·재공략 실성과 미연결. Mock 캠페인 관측 및 Forecast는 GA4 실적에 합산하지 않습니다.</p></html>`,"text/html;charset=utf-8");};
 return <div className="mvp ga4-view"><div className="mvp-heading"><div><h2>{page==="reports"?"Executive Report":page==="funnel"?"GA4 Funnel Events":page==="performance"?"REAL BASELINE + DEMO FORECAST":"GA4 Overview"}</h2><p>{s.period}일 · {s.startDate} ~ yesterday · {s.timezone} · READ ONLY</p></div>{page==="reports"&&<button onClick={exportReport}>Executive HTML Export</button>}</div><p>Data Sources: GA4 · REAL / Meta · MOCK / 예상 성과 · DEMO</p><div className="mvp-kpis">{[["Users",number(o.users)],["Sessions",number(o.sessions)],["Purchase (건)",number(o.purchases)],[`Purchase Revenue (${o.currency})`,money(o.purchaseRevenue)]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>{s.warnings.map(w=><p className="mvp-error" role="status" key={w}>{w}</p>)}{!o.users&&!o.sessions&&<p>조회 기간에 GA4 데이터가 없습니다. Mock 수치로 대체하지 않습니다.</p>}
 {page==="performance"?<section><h2>실제 현재 성과을 기준으로 구매 개선 가정</h2><p>GA4 이벤트별 집계는 순차 코호트가 아니므로 기존 Mock 순차 퍼널 엔진에 강제 변환하지 않습니다. 실제 이벤트 사용자와 구매 건수를 보존하고 구매율 변화만 비교합니다. 광고 예산·재공략 레버는 실측 근거가 없어 비활성화됩니다.</p><label>구매 개선 가정 (%)<input type="range" min={-30} max={30} value={lift} onChange={e=>setLift(Number(e.target.value))}/><input aria-label="GA4 구매 개선 값" type="number" min={-30} max={30} value={lift} onChange={e=>setLift(Math.max(-30,Math.min(30,Number(e.target.value)||0)))}/></label><div className="ga4-actions">{scenarios.map(x=><button key={x.id} onClick={()=>setLift(x.levers.checkout)}>{x.name}</button>)}<button onClick={()=>setLift(0)}>Reset</button></div><p>DEMO FORECAST · 구매 {number(forecast.purchases)}건 / 매출 {money(forecast.purchaseRevenue)} · 현재 구매 {number(o.purchases)}건 대비 {forecast.purchases-o.purchases}건</p><p>평균 구매 매출 고정·상대 구매율 {lift}% 변화 가정이며 통계적 성과 보장이 아닙니다.</p></section>:<section><h2>Funnel · 이벤트별 GA4 사용자</h2><div className="mvp-scroll"><table><thead><tr><th>Event</th><th>Distinct Users</th><th>Availability</th></tr></thead><tbody><tr><th>Traffic</th><td>{number(o.users)}명</td><td>totalUsers</td></tr>{s.events.map(event=><tr key={event.key}><th>{event.eventName}</th><td>{number(event.users)}명</td><td>{event.found?"FOUND":"EVENT NOT DETECTED"}</td></tr>)}</tbody></table></div><p>각 이벤트의 totalUsers입니다. 이벤트 순서·교집합을 조회한 코호트가 아니므로 단계 간 전환율·이탈·미구매 고객 그룹를 계산하지 않습니다. Purchase KPI는 사용자 수가 아닌 ecommercePurchases입니다.</p></section>}
 <section><h2>유입 경로s · 상위 20개</h2><p>Source별 Users는 중복될 수 있어 합산해 전체 Unique로 사용하지 않습니다. GPT 분류는 Source/Medium alias 기반이며 광고 플랫폼 인증 여부를 뜻하지 않습니다.</p><div className="mvp-scroll"><table><thead><tr><th>Source / Medium</th><th>분류</th><th>Users</th><th>Sessions</th><th>Purchases</th><th>Purchase Revenue</th></tr></thead><tbody>{s.sources.map(r=><tr key={r.id}><th>{r.sourceMedium}</th><td>{r.classification}</td><td>{r.users}</td><td>{r.sessions}</td><td>{r.purchases}</td><td>{money(r.purchaseRevenue)}</td></tr>)}</tbody></table></div>{!s.sources.length&&<p>유입 소스 데이터가 없습니다.</p>}</section>
 {page==="reports"&&<><section><h2>REAL BASELINE + DEMO FORECAST</h2><p>설정한 시나리오의 구매율 개선 가정 · 현재 {o.purchases}건 → 예상 {forecast.purchases}건 / {money(forecast.purchaseRevenue)}</p><p>평균 구매 매출을 고정한 가정입니다. 광고비·재공략 효과는 포함하지 않습니다.</p></section><MockReportSummary query={query}/></>}{(page==="reports"||page==="overview")&&<GA4DailyTable/>}<section><h2>광고 성과 · MOCK AD DATA</h2><p>Spend / CPA / ROAS / 재방문 구매 실측은 미연결입니다. 기존 Mock 캠페인·고객 그룹·운영은 별도 화면에서 검토하며 GA4 구매와 합산하지 않습니다.</p><div className="ga4-actions"><Link href="/performance">GA4 현재 성과 시뮬레이션 →</Link><Link href={`/campaigns?advertiser=${query.advertiserId}&period=${query.period}`}>Mock 캠페인 설계 →</Link><Link href={`/operations?advertiser=${query.advertiserId}&period=${query.period}`}>Mock 운영 상태 →</Link><Link href="/connections">GA4 연결 상세 →</Link></div></section></div>;
}
export function GA4DailyTable(){const {data}=useGA4(),s=data?.snapshot;if(!s)return null;return <section className="mvp"><h2>Daily GA4 Data · REAL GA4 DATA</h2><p>GA4 Property 날짜 기준입니다. 날짜별 Users는 기간 Unique와 합산 비교할 수 없습니다. 실제 광고비·CPA·ROAS는 표시하지 않습니다.</p><div className="mvp-scroll"><table><thead><tr><th>Date</th><th>Users</th><th>Sessions</th><th>Purchase</th><th>Purchase Revenue ({s.overview.currency})</th></tr></thead><tbody>{s.daily.map(r=><tr key={r.date}><th>{r.date}</th><td>{r.users}</td><td>{r.sessions}</td><td>{r.purchases}</td><td>{number(r.purchaseRevenue)}</td></tr>)}</tbody></table></div>{!s.daily.length&&<p>일별 데이터가 없습니다.</p>}</section>;}
