"use client";
import {useState} from "react";
import {useGA4} from "./provider";
import {readGA4} from "@/lib/ga4/browser-service";
import type {GA4Envelope} from "@/types/ga4";
export function GA4ConnectionControls(){const {data,mode,changeMode,query,refresh}=useGA4(),[result,setResult]=useState<GA4Envelope|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const state=result?.connection??data?.connection,snapshot=result?.snapshot;
 const request=async(action:"test"|"snapshot")=>{setBusy(true);setError("");try{const response=await readGA4({...query,period:30},"real",action);setResult(response);if(action==="test")refresh();if(response.error)setError(response.error.message);}catch{setError("GA4 서버 응답을 확인하지 못했습니다.");}finally{setBusy(false);}};
 return <section className="ga4-controls"><h3>GA4 Read Only Connection</h3><label>GA4 Data Mode<select value={mode} disabled={busy} onChange={e=>{setResult(null);setError("");changeMode(e.target.value as "mock"|"real");}}><option value="mock">Mock</option><option value="real">GA4 Real</option></select></label><p><b>{state?.status??"상태 확인 중"}</b> · READ ONLY</p>{state?.status==="NOT CONFIGURED"&&<p>CONFIGURATION REQUIRED · GA4 Property ID와 서버 Service Account 설정이 필요합니다.</p>}<p>Property ID: {state?.propertyId??"미설정"} · Last Tested: {state?.lastTested??"아직 테스트하지 않음"}</p><p>Quota Status · 시간당 잔여 토큰: {state?.quotaRemaining??"미조회"}</p><div className="ga4-actions"><button disabled={busy} onClick={()=>request("test")}>연결 테스트</button><button disabled={busy} onClick={()=>request("snapshot")}>최근 30일 검증 / Source Inspector</button></div>{busy&&<p role="status">서버에서 GA4 읽기 요청 중…</p>}{(error||state?.error)&&<p role="alert">{error||state?.error?.message}</p>}{snapshot&&<><h3>GA4 Data Validation · REAL GA4 DATA</h3><p>Users {snapshot.overview.users} · Sessions {snapshot.overview.sessions} · Purchase {snapshot.overview.purchases} · Purchase Revenue {snapshot.overview.purchaseRevenue} {snapshot.overview.currency}</p>{snapshot.events.map(e=><p key={e.key}>{e.eventName} · {e.found?"FOUND":"NOT FOUND"} · {e.users} users</p>)}{snapshot.warnings.map(w=><p key={w}>{w}</p>)}<h3>유입 경로 Inspector · 최근 30일 상위 20개</h3><div className="mvp-scroll"><table><thead><tr><th>Source</th><th>Medium</th><th>분류</th><th>Sessions</th></tr></thead><tbody>{snapshot.sources.map(s=><tr key={s.id}><td>{s.source}</td><td>{s.medium}</td><td>{s.classification}</td><td>{s.sessions}</td></tr>)}</tbody></table></div>{!snapshot.sources.length&&<p>조회된 Source가 없습니다.</p>}</>}<p>Credential은 서버 파일에서만 읽습니다. Service Account Email/Private Key를 이 화면에 입력하거나 표시하지 않습니다. Real 조회는 로컬 개발 서버에서만 활성화됩니다.</p></section>;
}
