import type { GA4Overview,GA4Event,GA4Daily,GA4TrafficSource,FunnelEventMapping } from "../../types/ga4";
import { classifySource,defaultSourceRules,type SourceRules } from "./definitions";
export interface ReportResponse { rows?:{dimensionValues?:{value?:string|null}[]|null;metricValues?:{value?:string|null}[]|null}[]|null;metricHeaders?:{name?:string|null}[]|null;dimensionHeaders?:{name?:string|null}[]|null;metadata?:{currencyCode?:string|null;timeZone?:string|null;subjectToThresholding?:boolean|null;dataLossFromOtherRow?:boolean|null;samplingMetadatas?:unknown[]|null}|null;propertyQuota?:{tokensPerHour?:{remaining?:number|null}|null}|null;rowCount?:number|null }
export function rows(response:ReportResponse){return (response.rows??[]).map(r=>Object.fromEntries([...(response.dimensionHeaders??[]).map((h,i)=>[h.name??"",r.dimensionValues?.[i]?.value??""]),...(response.metricHeaders??[]).map((h,i)=>[h.name??"",r.metricValues?.[i]?.value??"0"])]));}
const num=(v:string|undefined)=>{const n=Number(v??0);return Number.isFinite(n)?Math.max(0,n):0;};
export const overviewRow=(r:Record<string,string>,currency="KRW"):GA4Overview=>({users:num(r.totalUsers),sessions:num(r.sessions),purchases:num(r.ecommercePurchases),purchaseRevenue:Number.isFinite(Number(r.purchaseRevenue))?Number(r.purchaseRevenue):0,currency});
export const normalizeOverview=(r:ReportResponse)=>overviewRow(rows(r)[0]??{},r.metadata?.currencyCode??"KRW");
export function normalizeEvents(r:ReportResponse,mapping:FunnelEventMapping):GA4Event[]{const data=rows(r);return Object.entries(mapping).map(([key,eventName])=>{const row=data.find(v=>v.eventName===eventName);return {key:key as keyof FunnelEventMapping,eventName,users:num(row?.totalUsers),found:!!row};});}
export function normalizeSources(r:ReportResponse,rules:SourceRules=defaultSourceRules):GA4TrafficSource[]{return rows(r).map(row=>({id:JSON.stringify([row.sessionSource,row.sessionMedium]),name:row.sessionSourceMedium||`${row.sessionSource} / ${row.sessionMedium}`,source:row.sessionSource??"(not set)",medium:row.sessionMedium??"(not set)",sourceMedium:row.sessionSourceMedium??"(not set)",...classifySource(row.sessionSource??"",row.sessionMedium??"",rules),...overviewRow(row)}));}
export function normalizeDaily(r:ReportResponse):GA4Daily[]{return rows(r).filter(row=>/^\d{8}$/.test(row.date??"")).map(row=>({...overviewRow(row,r.metadata?.currencyCode??"KRW"),date:`${row.date.slice(0,4)}-${row.date.slice(4,6)}-${row.date.slice(6,8)}`}));}
